### ISSUE TITLE
View My Profile: Point Labels Contain the Number 1

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#10]
Go to profile page and powers have the number 1 appended - e.g. Curiosity1

<img width="377" alt="labels_with_ones" src="https://cloud.githubusercontent.com/assets/273429/15727556/f18001a6-281c-11e6-886a-864292e9196c.png">

**Comment by Guihrmsfo** [comment]
@nathanverrill
Fixed.
