### ISSUE TITLE
Sometimes I have to click log out twice to log out.

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#103]

**Comment by nathanverrill** [comment]
I've actually had this issue for awhile but had not logged it. Something we might look into later.

**Comment by rjapur** [comment]
We could not replicate the issue. Also, talked to Lucas and he's unware of this bug.

**Comment by nathanverrill** [comment]
Weird! It happens to me quite frequently on Mac/Chrome. (just did a little while ago as well).  Perhaps it is because I log in as so many different users. Not a huge thing, just something to be aware of.

**Comment by rjapur** [comment]
Talked to Lucas again yesterday about this issue and it's from humhub, so we'll have to wait a fix from his team
