### ISSUE TITLE
Scrolling to the top of the page shows the success pop-up again.

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#106]
To recreate:

Submit evidence
Success Message is displayed - do not click close
Scroll to top
Success Message is displayed again

It looks like additional points are not added.... 

The user Safari Layout had it happen when they submitted M2A5
Safari Layout / pw: Soacha

**Comment by Guihrmsfo** [comment]
Could not recreate, not happening anymore.
