### ISSUE TITLE
Photo upload not working on prod (but works on dev)

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#108]
Tried uploading the same photos, both jpg and png, and uploaded in comment box and status update successfully on dev. On prod, the bar where the buttons are go blank after hitting the cloud up arrow and choosing the photo.

**Comment by JayantGandhi** [comment]
@rjapur @Guihrmsfo, do either of you guys have a guess as to why just the photo upload for the status updates and comments would not work? Uploads seem to be working everywhere else (like in the admin and the profile pages)

**Comment by JayantGandhi** [comment]
```
{name: "PHP Warning", message: "mkdir(): No such file or directory", code: 2,…}
code
:
2
file
:
"/home/ubuntu/humhub/protected/humhub/modules/file/models/File.php"
line
:
179
message
:
"mkdir(): No such file or directory"
name
:
"PHP Warning"
stack-trace
:
[,…]
type
:
"yii\base\ErrorException"
```

**Comment by JayantGandhi** [comment]
fixed
