### ISSUE TITLE
Deleting an evidence doesn't take away points

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#111]
Submit some evidence
As an admin, go to that player's profile and delete all of their evidence
Points remain

**Comment by JayantGandhi** [comment]
It might be better to just not allow them to delete their evidence... Like with a homework assignment, once you hand it in, you don't get to take it back.

**Comment by nathanverrill** [comment]
Excellent! I'll close and add to pivotal.

**Comment by nathanverrill** [comment]
Changing requirement to not allow players to delete their evidence.

Note that edit should remain... Especially with admins in case we need to edit offensive content.
