### ISSUE TITLE
On some powers, points to level up 1 less than in levels spreadsheet

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#114]
Spoke with gui, probably rounding
Not a big deal, but wanted to capture it.

<img width="829" alt="off-by-one" src="https://cloud.githubusercontent.com/assets/273429/17676606/f6c0ce6c-62f4-11e6-83fd-6632922e01af.png">

**Comment by JayantGandhi** [comment]
yeah, my guess it's a difference in how php vs spreadsheets do their rounding...doesn't really change anything since all the levels have an expected error of 2 pts

**Comment by nathanverrill** [comment]
Related to this issue, when you exactly match a level requirement in whole numbers - so for example if you get +100 communication with a 100pt requirement... It shows Level 0 with 0 points needed to level, so looks like a bug.

<img width="681" alt="level_0_when_0_remaining" src="https://cloud.githubusercontent.com/assets/273429/17677555/f1eb6556-62f8-11e6-87fe-d2a8af0b96d8.png">
