### ISSUE TITLE
Review Evidence link not displayed for admins or mentors in top navigation

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#118]
Home, Directory, Leaderboard and Graphic Novel are the only links displayed.

<img width="1156" alt="mentor_links" src="https://cloud.githubusercontent.com/assets/273429/17680161/7cc1f338-6304-11e6-8044-100992b030de.png">

**Comment by JayantGandhi** [comment]
we need to have the mentors group made and the mentor needs to be a member of it
