### ISSUE TITLE
Only one space is listed in the directory

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#138]
see attached screenshot
go to directory and choose spaces

<img width="1054" alt="just-one-space" src="https://cloud.githubusercontent.com/assets/273429/17950331/30910742-6a20-11e6-8196-9f94b84356e6.png">

**Comment by Guihrmsfo** [comment]
@nathanverrill 
Please, verify for me if those hidden spaces aren't visible on: 
space -> gear button -> general -> security ->visibility.
I guess probably that's the issue cause.

**Comment by nathanverrill** [comment]
public spaces are missing too, I can navigate to them from the "new spaces"
box on the right of the directory. spaces should be set to default public
visibility

**Comment by nathanverrill** [comment]
For example, this one:

http://soacha.evokenet.org/index.php?r=space%2Fmanage%2Fdefault%2Fsecurity&sguid=a707657a-fce4-44b9-b1e5-749ea45d4083

Is set to public and not in the directory

**Comment by Guihrmsfo** [comment]
I need administrator permission to see that.
Can you give me permission?
Users:
Mentor G Fernandes
Guihrmsfo

**Comment by nathanverrill** [comment]
done!

**Comment by Guihrmsfo** [comment]
Thanks!

**Comment by Guihrmsfo** [comment]
Nathan, I really don't know its cause and I don't think it's a query bug, but probably something else, gotta find out yet.
But.. I tried to turn this example space you gave me to private configuration and turned out again to public, and then it appeared!
Could you try on another space too, please?

**Comment by nathanverrill** [comment]
Odd. You can pick a space in the admin panel and navigate over to it to
try. I just picked one, checked its settings, and then did a search on the
spaces directory to see if it would come up. make sense?

**Comment by Guihrmsfo** [comment]
Yeah, It does!
I just tried again and this time I didn't try turning to private, I just left the way it is and updated. And worked as well!
I guess all those public spaces are locked to private in someway and now we gotta update manually.
Did you remember how were the configurations for space creation? And all the times you've changed?
We have to track this 'cause I think that's probably the real issue.

**Comment by nathanverrill** [comment]
I put in the wiki, the settings that are updated in the admin

**Comment by Guihrmsfo** [comment]
I think that happens the same case for content visibility.
If you create a space before changing 'Default Visibility' setting to public, all spaces will be private and we'd have to update them manually.

**Comment by nathanverrill** [comment]
Default visibility\* is\* public, so how do do you think they get changed?

**Comment by nathanverrill** [comment]
Or, does the default visibility setting in the admin not affect teams?

**Comment by Guihrmsfo** [comment]
It should affect.
So, the visibility setting have never been private? I thought it used to be private at the begin, then users created some spaces and after that we changed the setting.

**Comment by nathanverrill** [comment]
My recollection is that they were originally public (because I could see
them) and then we had a deployment and then in QA I noticed that were no
longer in the directory and therefor private until we changed it manually.

Note that some players are not appearing in the directory search either.
Maybe they're related somehow.
