### ISSUE TITLE
Incorrect Timestamp - About an Hour Ago

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#14]
If I post content, the timestamp displayed right after says 'one hour ago'

**Comment by nathanverrill** [comment]
Any progress on this issue with the timestamp?

**Comment by nathanverrill** [comment]
If this becomes a huge lift, feel free to hide the time stamp if possible (using css or similar simple approach) so user's don't see that it's an issue.

**Comment by nathanverrill** [comment]
Closing since we addressed by hiding the timestamp feature. adding feature to pivotal for this and the chronological order bug.

**Comment by stonepilot** [comment]
Was the Incorrect Timestamp - About an Hour Ago issue ever fixed?  That was 4 years ago and I'm seeing it myself.
