### ISSUE TITLE
No error message when uploading large video file

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#142]
I tried uploading a 9mb file to attach to my evidence to see what would happen if I used a large file. This is part of investigating the issue that a player is having where their uploaded video shows 0mb.

I wasn't able to recreate the issue that the player had, but did find out that there's no error message.

**Comment by nathanverrill** [comment]
The UX solution is to prevent video filetypes and include a message to the player to use YouTube for videos. Include a link to the YouTube video upload page.

**Comment by Guihrmsfo** [comment]
![image](https://cloud.githubusercontent.com/assets/3788902/23757497/c6593322-04c5-11e7-9700-88f9660df18d.png)
