### ISSUE TITLE
broken permalink

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#144]
I shared the following link with Bob with a question about an evidence:

http://soacha.evokenet.org/index.php?r=missions%2Fevidence%2Fshow&activityId=6&sguid=a57f358d-9097-4b2e-868e-5a62c0fb8525

I accessed the permalink by hitting the caret on the post and choosing permalink.

He received the attached error when he attempted to view it.

![broken-permalink](https://cloud.githubusercontent.com/assets/273429/18004842/1a0c6e0c-6b5c-11e6-8e88-b7f1bd809d1e.png)

**Comment by JayantGandhi** [comment]
works for me... can you confirm this link still doesn't work?

**Comment by nathanverrill** [comment]
OK, the only way I could recreate was when I was logged out (I tried with
existing account and new account in both English and Spanish)

**Comment by JayantGandhi** [comment]
@nathanverrill, yeah, if you're logged out you shouldn't be able to view that page. Debug mode accidentally got turned back on in production in one of the merges. I disabled it again, so instead of that error you should get the default humhub page not found error.
