### ISSUE TITLE
Some players don't show up in directory search

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#147]
maybe it's because these players used a @ sign in their username, for example arnol09@hotmail.com?

<img width="1059" alt="not-in-search-results-2" src="https://cloud.githubusercontent.com/assets/273429/18068700/57e91ce4-6e08-11e6-9169-324fa8293973.png">
<img width="1060" alt="not-in-search-results" src="https://cloud.githubusercontent.com/assets/273429/18068701/57ede224-6e08-11e6-8b8c-89022e768b07.png">

**Comment by nathanverrill** [comment]
Hmmm, here's another user that doesn't show up in member search: Michell

**Comment by rjapur** [comment]
According to Lucas, the search in the directory doesn't handle special characters like @ that's why nothing is returned. Over the next interations of humhub, this bug will be fixed
