### ISSUE TITLE
Previously submitted reviews not visible after clicking Reviews

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#156]
<img width="738" alt="no-reviews-visible" src="https://cloud.githubusercontent.com/assets/273429/18317669/5f230c80-74e4-11e6-92f3-de3c45827e3d.png">

**Comment by JayantGandhi** [comment]
can't recreate... I can see reviews if a evidence has already been reviewed.

**Comment by JayantGandhi** [comment]
![image](https://cloud.githubusercontent.com/assets/4398613/18322631/997cb120-7501-11e6-8cd6-732a81959152.png)

**Comment by nathanverrill** [comment]
Still an issue when logged in as Rio Misisipi, have a look at:

http://soacha.evokenet.org/index.php?r=space%2Fspace&wallEntryId=655&sguid=a57f358d-9097-4b2e-868e-5a62c0fb8525

This is after clicking on the notification, viewing my own evidence:

<img width="1150" alt="review-not-shown" src="https://cloud.githubusercontent.com/assets/273429/18437462/a5ff28f0-78c2-11e6-9aae-a0743061688e.png">

<img width="1195" alt="review-notification" src="https://cloud.githubusercontent.com/assets/273429/18437470/b16decbc-78c2-11e6-8f4a-3a23ec79dacf.png">

**Comment by JayantGandhi** [comment]
@nathanverrill: still can't replicate after becoming rio missippi, the deploy today might have fixed it. Can you double check?
