### ISSUE TITLE
Users show 2 spaces in header, but no link to team

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#164]
Andrea Ramírez
Camilo Martinez
jhon.alux666qgmail.com
cami.30

No link to teams on their profile pages

**Comment by Guihrmsfo** [comment]
Bug fix on dev.
The user doesn't belong to a team yet, he's just been invited.
So I fixed the spaces information on profile header.

**Comment by Guihrmsfo** [comment]
Hi, @nathanverrill 
What's the status for this issue? It seems I removed the QA label (but I can't remember that or even why I did that, maybe an unnoticed miss click?)

**Comment by nathanverrill** [comment]
2 are all set, the other 2 have never logged in. Closing.
