### ISSUE TITLE
"Undefined variable: user_fixed" Error when trying to view mentor profile

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#166]
http://soacha.evokenet.org/index.php?r=user%2Fprofile&uguid=e47a3d71-47e7-45e3-8e9a-5b1bdc1b0b44

PHP Notice – yii\base\ErrorException

Undefined variable: user_fixed
1. in /home/ubuntu/humhub/themes/Evoke/views/user/widgets/profileHeader.php at line 210
201202203204205206207208209210211212213214215216217218219                        <div class="pull-left entry">
                            <span
                                class="count"><?php echo $user->getFollowingCount(User::className()); ?></span>
                            <br>
                            <span
                                class="title"><?php echo Yii::t('UserModule.widgets_views_profileHeader', 'Following'); ?></span>
                        </div>

```
                    <div class="pull-left entry">
                        <span class="count"><?php echo count($user_fixed->spaces); ?></span><br>
                        <span
                            class="title"><?php echo Yii::t('UserModule.widgets_views_profileHeader', 'Spaces'); ?></span>
                    </div>

                </div>
                <!-- end: User statistics -->

                <div class="controls controls-header pull-right">
                    <?php
```
1. in /home/ubuntu/humhub/themes/Evoke/views/user/widgets/profileHeader.php at line 210 – yii\base\ErrorHandler::handleError(8, 'Undefined variable: user_fixed', '/home/ubuntu/humhub/themes/Evoke...', 210, ...)
   204205206207208209210211212213214215216                            <br>
                           <span
                               class="title"><?php echo Yii::t('UserModule.widgets_views_profileHeader', 'Following'); ?></span>
                       </div>
   
   ```
                   <div class="pull-left entry">
                       <span class="count"><?php echo count($user_fixed->spaces); ?></span><br>
                       <span
                           class="title"><?php echo Yii::t('UserModule.widgets_views_profileHeader', 'Spaces'); ?></span>
                   </div>
   
               </div>
               <!-- end: User statistics -->
   ```
2. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/home/ubuntu/humhub/themes/Evoke...')
3. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/var/www/html/humhub/themes/Evok...', ['user' => humhub\modules\user\models\User, 'isProfileOwner' => false])
4. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/home/ubuntu/humhub/protected/hu...', ['user' => humhub\modules\user\models\User, 'isProfileOwner' => false], humhub\modules\user\widgets\ProfileHeader)
5. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Widget.php at line 191 – yii\base\View::render('profileHeader', ['user' => humhub\modules\user\models\User, 'isProfileOwner' => false], humhub\modules\user\widgets\ProfileHeader)
6. in /home/ubuntu/humhub/protected/humhub/modules/user/widgets/ProfileHeader.php at line 62 – yii\base\Widget::render('profileHeader', ['user' => humhub\modules\user\models\User, 'isProfileOwner' => false])
   565758596061626364656667     */
   public function run()
   {
       return $this->render('profileHeader', array(
                   'user' => $this->user,
                   'isProfileOwner' => $this->isProfileOwner
       ));
   }

}

?>
8. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Widget.php at line 98 – humhub\modules\user\widgets\ProfileHeader::run()
9. in /home/ubuntu/humhub/themes/Evoke/views/user/profile/_layout.php at line 12 – yii\base\Widget::widget(['user' => humhub\modules\user\models\User])
6789101112131415161718        <div class="col-sm-12">
            <?php 

```
        if($user->group->name != "Mentors"){
            echo \humhub\modules\stats\widgets\CustomProfileHeader::widget(['user' => $user]); 
        }else{
            echo \humhub\modules\user\widgets\ProfileHeader::widget(['user' => $user]);
        }

        ?>
    </div>
</div>
<div class="row">
```
1. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/home/ubuntu/humhub/themes/Evoke...')
2. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/var/www/html/humhub/themes/Evok...', ['content' => ' <ul class="nav nav-tabs wal...'])
3. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/home/ubuntu/humhub/protected/hu...', ['content' => ' <ul class="nav nav-tabs wal...'], null)
4. in /home/ubuntu/humhub/themes/Evoke/views/layouts/main.php at line 120 – yii\base\View::render('@humhub/modules/user/views/profi...', ['content' => ' <ul class="nav nav-tabs wal...'])
   114115116117118119120121122123124125126    
   
   <?php echo \humhub\modules\tour\widgets\Tour::widget(); ?>
   
   
   
   <?php if (isset($this->context->subLayout) && $this->context->subLayout != "") : ?>
       <?php echo $this->render($this->context->subLayout, array('content' => $content)); ?>
   <?php else: ?>
       <?php echo $content; ?>
   <?php endif; ?>
   
   
   
   
5. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/home/ubuntu/humhub/themes/Evoke...')
6. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/var/www/html/humhub/themes/Evok...', ['content' => ' <ul class="nav nav-tabs wal...'])
7. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 392 – yii\base\View::renderFile('/home/ubuntu/humhub/protected/hu...', ['content' => ' <ul class="nav nav-tabs wal...'], humhub\modules\user\controllers\ProfileController)
8. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 378 – yii\base\Controller::renderContent(' <ul class="nav nav-tabs wal...')
9. in /home/ubuntu/humhub/protected/humhub/modules/user/controllers/ProfileController.php at line 57 – yii\base\Controller::render('index', ['user' => humhub\modules\user\models\User])
   51525354555657585960616263 
   /**
    *
    */
   public function actionIndex()
   {
       return $this->render('index', ['user' => $this->contentContainer]);
   }
   
   /**
    *
    */
   public function actionAbout()
10. humhub\modules\user\controllers\ProfileController::actionIndex()
11. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\user\controllers\ProfileController, 'actionIndex'], [])
12. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'user/profile', 'uguid' => 'e47a3d71-47e7-45e3-8e9a-5b1bdc1b...'])
13. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('', ['r' => 'user/profile', 'uguid' => 'e47a3d71-47e7-45e3-8e9a-5b1bdc1b...'])
14. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('user/profile', ['r' => 'user/profile', 'uguid' => 'e47a3d71-47e7-45e3-8e9a-5b1bdc1b...'])
15. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
16. in /home/ubuntu/humhub/index.php at line 25 – yii\base\Application::run()
    19202122232425    require(**DIR** . '/protected/humhub/config/web.php'),
    (is_readable(**DIR** . '/protected/config/dynamic.php')) ? require(**DIR** . '/protected/config/dynamic.php') : [],
    require(**DIR** . '/protected/config/common.php'),
    require(**DIR** . '/protected/config/web.php')
    );

(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'user/profile',
    'uguid' => 'e47a3d71-47e7-45e3-8e9a-5b1bdc1b0b44',
];

$_COOKIE = [
    '_csrf' => 'd6be1d76c7d83948ca174889be9b214adb009dde13c31719f6cbe1763de07a82a:2:{i:0;s:5:"_csrf";i:1;s:32:"VesgbGVLJtsCOt_cTWFmMkfjsyrDOvnM";}',
    'pm_space-members-panel' => 'expanded',
    'pm_profile-following-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'pm_profile-follower-panel' => 'expanded',
    'pm_groups-statistics-panel' => 'expanded',
    'pm_new-people-panel' => 'expanded',
    'pm_user-statistics-panel' => 'expanded',
    'pm_new-spaces-panel' => 'expanded',
    '_gat' => '1',
    'language' => '2e2c7fa0242766f45a734a15a20a634d37b58d606f6f05f0aad08c2640adbbeea:2:{i:0;s:8:"language";i:1;s:2:"es";}',
    'PHPSESSID' => 'sit16e17s09p2uhlqui0jk6hi6',
    '_ga' => 'GA1.2.1926725822.1471014321',
    '_identity' => '59ae5cccac10c04bf5e1113b038afbe1d9553e85c93d4bef0e9d3699a3270fe1a:2:{i:0;s:9:"_identity";i:1;s:51:"[48,"73ec8dfe-93f3-406d-a15f-b86151b8bbff",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/index.php',
    '__id' => 48,
];
Yii Framework
2016-09-12, 15:31:20

Apache/2.4.7 (Ubuntu)
Yii Framework/2.0.7

<img width="1183" alt="broken-mentor-link" src="https://cloud.githubusercontent.com/assets/273429/18451826/20a028da-78fe-11e6-8155-046de932ff39.png">

**Comment by JayantGandhi** [comment]
fixed
