### ISSUE TITLE
Activity Page Lists Evidences for All Missions and Activities, not just that activity

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#17]
To recreate:

1) navigate to Mission 1, Activity 1. Enter an evidence with a name "Mission 1, Activity 1"

2) navigate to Mission 1, Activity 2. Note that Mission 1, Activity 1 evidence is underneath the entry box. Enter another evidence with the name "Mission 1, Activity 2"

3) navigate to Mission 2, Activity 1. Note that both of the evidences above are listed on the page. 

Instead, each activity page should only display evidence specific to that activity, not all evidences.

<img width="903" alt="activity1_and_2" src="https://cloud.githubusercontent.com/assets/273429/15987760/b441a926-2ffa-11e6-9fe6-21696c0d4d91.png">
<img width="901" alt="mission_list" src="https://cloud.githubusercontent.com/assets/273429/15987761/b452be64-2ffa-11e6-8919-4da37298426c.png">

**Comment by Guihrmsfo** [comment]
Fixed.
