### ISSUE TITLE
Mentor Submitted 3 for a review, shows as a 0 in the reviews listing

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#173]
http://soacha.evokenet.org/index.php?r=space%2Fspace&wallEntryId=1745&sguid=0932c0a6-6d6e-4486-8a98-69d97018bb78

From Vivi:
Mentor Tatiana Martinez contacted Marta because she review some evidence with 3 but it appears with 0
it's from JhMedinaM, Mission 1 Activity 5
can you change the number?

<img width="489" alt="review-zero-not-three" src="https://cloud.githubusercontent.com/assets/273429/18638572/48d81148-7e56-11e6-9d26-6ae167e0a856.png">

**Comment by JayantGandhi** [comment]
Done
