### ISSUE TITLE
Says "woops something's wrong" when reviewing evidence and leaving comment empty

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#175]
Login as mentor
Follow a team
Review an evidence for that team after navigating: Review Evidence > Choose Activity 
Select Yes, Give it a 5 and leave the comment blank

http://dev.humhub.m00.com.br/index.php?r=missions%2Fevidence%2Fmentor&activityId=14&sguid=6dd4741a-fbbf-4bde-adde-f92c7fb1ef78

<img width="484" alt="woops" src="https://cloud.githubusercontent.com/assets/273429/18795327/aad1c6d8-8189-11e6-9af5-9769a7e9f74f.png">

<img width="807" alt="popuperror" src="https://cloud.githubusercontent.com/assets/273429/18795338/bc0f3d7c-8189-11e6-8f0f-675b34e9509e.png">

**Comment by JayantGandhi** [comment]
~~same issue as #181~~

**Comment by Guihrmsfo** [comment]
Issue #181 fixed
