### ISSUE TITLE
Points Earned Confirmation Singular when just 1 point

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#18]
Currently if I submit evidence and it is just 1 point awarded, it says "points" instead of the singular "point"

<img width="623" alt="singular" src="https://cloud.githubusercontent.com/assets/273429/16019217/6e9870e8-316d-11e6-8a55-464f9af2f2ef.png">

**Comment by Guihrmsfo** [comment]
@nathanverrill 
Fixed.
