### ISSUE TITLE
Mission 1 Title repeated on evidence title when reviewing

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#180]
See attached

<img width="885" alt="mission_title_repeated_on_evidence_review" src="https://cloud.githubusercontent.com/assets/273429/18815712/e905e1da-82fd-11e6-9fa0-1d5caffb8194.png">

**Comment by JayantGandhi** [comment]
Issue on the admin side, won't be a problem on production since "Mission 1" isn't included in the title (it is on dev for some reason)
