### ISSUE TITLE
Cannot add Evokation link to Evokation page

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#196]
I tried as a player and a captain

<img width="891" alt="add-evokation-link" src="https://cloud.githubusercontent.com/assets/273429/19161510/b24cf5a6-8bb9-11e6-946a-edded46a0815.png">

**Comment by JayantGandhi** [comment]
looks like it's not appearing because there is no evokation for the team(s)

@Guihrmsfo @rjapur: when does the create evokation action happen? It seems to have not happened on production for some reason...

**Comment by Guihrmsfo** [comment]
You can only submit an evidence if first checkbox is checked (Evoke Settings page).

![image](https://cloud.githubusercontent.com/assets/3788902/19242010/b4431800-8ee7-11e6-934b-067846d867a0.png)

And it's correct, the link's not appearing 'cause there's no evokation submitted by that team leader.

**Comment by nathanverrill** [comment]
I don't understand...

 Sent from my walkie talkie

   This (https://itunes.apple.com/app/apple-store/id922793622?pt=814382&mt=8&ct=how_i_email)  is how I Email now

**Comment by Guihrmsfo** [comment]
Google Drive URL should be available to edit before evokation submitting according to @nathanverrill 
Fix will be available soon.
