### ISSUE TITLE
Error on Login

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#203]
site was working when I was logged in...

PHP Notice – yii\base\ErrorException

Uninitialized string offset: 0
1. in /home/ubuntu/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Storage/File/AbstractFile.php at line 79
70717273747576777879808182838485868788     \* Reads an integer from the current position in the file
     \* and advances the file pointer.
     *
     \* @return integer
     */
    public function readInt()
    {
        $str = $this->_fread(4);

```
    return  ord($str[0]) << 24 |
            ord($str[1]) << 16 |
            ord($str[2]) << 8  |
            ord($str[3]);
}


/**
 * Writes an integer to the end of file.
 *
```
1. in /home/ubuntu/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Storage/File/AbstractFile.php at line 79 – yii\base\ErrorHandler::handleError(8, 'Uninitialized string offset: 0', '/home/ubuntu/humhub/protected/ve...', 79, ...)
   73747576777879808182838485     \* @return integer
    */
   public function readInt()
   {
       $str = $this->_fread(4);
   
   ```
   return  ord($str[0]) << 24 |
           ord($str[1]) << 16 |
           ord($str[2]) << 8  |
           ord($str[3]);
   ```
   
   }
2. in /home/ubuntu/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php at line 269 – ZendSearch\Lucene\Storage\File\AbstractFile::readInt()
   263264265266267268269270271272273274275     \* @throws \ZendSearch\Lucene\Exception\RuntimeException
    */
   private function _readSegmentsFile()
   {
       $segmentsFile = $this->_directory->getFileObject(self::getSegmentFileName($this->_generation));
   
   ```
   $format = $segmentsFile->readInt();
   
   if ($format == (int)0xFFFFFFFC) {
       $this->_formatVersion = self::FORMAT_2_3;
   } elseif ($format == (int)0xFFFFFFFD) {
       $this->_formatVersion = self::FORMAT_2_1;
   } else {
   ```
3. in /home/ubuntu/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Index.php at line 420 – ZendSearch\Lucene\Index::_readSegmentsFile()
   414415416417418419420421422423424425426 
       if ($this->_generation == -1) {
           throw new RuntimeException('Index doesn\'t exists in the specified directory.');
       } elseif ($this->_generation == 0) {
           $this->_readPre21SegmentsFile();
       } else {
           $this->_readSegmentsFile();
       }
   }
   
   /**
   - Object destructor
     */
4. in /home/ubuntu/humhub/protected/vendor/nqxcode/zendsearch/library/ZendSearch/Lucene/Lucene.php at line 67 – ZendSearch\Lucene\Index::__construct('/home/ubuntu/humhub/protected/ru...', false)
   61626364656667686970717273     *
   - @param mixed $directory
   - @return \ZendSearch\Lucene\SearchIndexInterface
     */
     public static function open($directory)
     {
     return new Index($directory, false);
     }
   
   /**
   - @throws \ZendSearch\Lucene\Exception\UnsupportedMethodCallException
     */
     public function __construct()
5. in /home/ubuntu/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php at line 266 – ZendSearch\Lucene\Lucene::open('/home/ubuntu/humhub/protected/ru...')
   260261262263264265266267268269270271272 
       \ZendSearch\Lucene\Search\QueryParser::setDefaultEncoding('utf-8');
       \ZendSearch\Lucene\Analysis\Analyzer\Analyzer::setDefault(new \ZendSearch\Lucene\Analysis\Analyzer\Common\Utf8Num\CaseInsensitive());
       \ZendSearch\Lucene\Search\QueryParser::setDefaultOperator(\ZendSearch\Lucene\Search\QueryParser::B_AND);
   
   ```
   try {
       $index = \ZendSearch\Lucene\Lucene::open($this->getIndexPath());
   } catch (\ZendSearch\Lucene\Exception\RuntimeException $ex) {
       $index = \ZendSearch\Lucene\Lucene::create($this->getIndexPath());
   }
   
   $this->index = $index;
   return $index;
   ```
6. in /home/ubuntu/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php at line 75 – humhub\modules\search\engine\ZendLuceneSearch::getIndex()
   69707172737475767778798081        $this->delete($object);
       $this->add($object);
   }
   
   public function delete(Searchable $obj)
   {
       $index = $this->getIndex();
   
   ```
   $query = new \ZendSearch\Lucene\Search\Query\MultiTerm();
   $query->addTerm(new \ZendSearch\Lucene\Index\Term($obj->className(), 'model'), true);
   $query->addTerm(new \ZendSearch\Lucene\Index\Term($obj->getPrimaryKey(), 'pk'), true);
   
   $hits = $index->find($query);
   ```
7. in /home/ubuntu/humhub/protected/humhub/modules/search/engine/ZendLuceneSearch.php at line 69 – humhub\modules\search\engine\ZendLuceneSearch::delete(humhub\modules\user\models\User)
   63646566676869707172737475        $index->addDocument($doc);
       $index->commit();
   }
   
   public function update(Searchable $object)
   {
       $this->delete($object);
       $this->add($object);
   }
   
   public function delete(Searchable $obj)
   {
       $index = $this->getIndex();
8. in /home/ubuntu/humhub/protected/humhub/modules/user/models/User.php at line 319 – humhub\modules\search\engine\ZendLuceneSearch::update(humhub\modules\user\models\User)
   313314315316317318319320321322323324325     *
   - @return type
     */
     public function afterSave($insert, $changedAttributes)
     {
     if ($this->status == User::STATUS_ENABLED) {
         Yii::$app->search->update($this);
     } else {
         Yii::$app->search->delete($this);
     }
     if ($insert) {
         if ($this->status == User::STATUS_ENABLED) {
             $this->setUpApproved();
9. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 739 – humhub\modules\user\models\User::afterSave(false, ['updated_at' => '2016-10-07 18:30:46', 'last_login' => '2016-10-07 18:30:46'])
10. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php at line 533 – yii\db\BaseActiveRecord::updateInternal(null)
11. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 595 – yii\db\ActiveRecord::update(true, null)
12. in /home/ubuntu/humhub/protected/humhub/modules/user/models/forms/AccountLogin.php at line 84 – yii\db\BaseActiveRecord::save()
    78798081828384858687888990     \* @return boolean whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate() && Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600 \* 24 \* 30 : 0)) {
            $this->_user->last_login = new Expression('NOW()');
            $this->_user->save();
            return true;
        } else {
            return false;
        }
    }
13. in /home/ubuntu/humhub/protected/humhub/modules/user/controllers/AuthController.php at line 59 – humhub\modules\user\models\forms\AccountLogin::login()
    53545556575859606162636465        if (!Yii::$app->user->isGuest) {
            $this->redirect(Yii::$app->user->returnUrl);
        }
    
    ```
    // Show/Allow Anonymous Registration
    $loginModel = new \humhub\modules\user\models\forms\AccountLogin;
    if ($loginModel->load(Yii::$app->request->post()) && $loginModel->login()) {
        if (Yii::$app->request->getIsAjax()) {
            return $this->htmlRedirect(Yii::$app->user->returnUrl);
        } else {
            return $this->redirect(Yii::$app->user->returnUrl);
        }
    }
    ```
14. humhub\modules\user\controllers\AuthController::actionLogin()
15. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\user\controllers\AuthController, 'actionLogin'], [])
16. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'user/auth/login'])
17. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('login', ['r' => 'user/auth/login'])
18. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('user/auth/login', ['r' => 'user/auth/login'])
19. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
20. in /home/ubuntu/humhub/index.php at line 25 – yii\base\Application::run()
    19202122232425    require(**DIR** . '/protected/humhub/config/web.php'),
    (is_readable(**DIR** . '/protected/config/dynamic.php')) ? require(**DIR** . '/protected/config/dynamic.php') : [],
    require(**DIR** . '/protected/config/common.php'),
    require(**DIR** . '/protected/config/web.php')
    );

(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'user/auth/login',
];

$_POST = [
    '_csrf' => 'RkFTNVN0Q2ggEyZTMQwJWicUN0IFEBVdKgMbVCQ3DAkvCh14PQ1uWQ==',
    'AccountLogin' => [
        'username' => 'Administrador',
        'password' => 'UrgentEvoke',
        'rememberMe' => '1',
    ],
];

$_COOKIE = [
    '_csrf' => '3f27e809c218cd69cc34a61cd77266324d0b08123809ab8e519f5bafb60de078a:2:{i:0;s:5:"_csrf";i:1;s:32:"fRufbxJ2aUdwVdV5lBHawCOaiKNMny-1";}',
    'pm_space-members-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'pm_profile-follower-panel' => 'expanded',
    'pm_profile-following-panel' => 'expanded',
    '_gat' => '1',
    'PHPSESSID' => 'er30eghei54qravtk1ba975g10',
    'language' => '2e2c7fa0242766f45a734a15a20a634d37b58d606f6f05f0aad08c2640adbbeea:2:{i:0;s:8:"language";i:1;s:2:"es";}',
    '_ga' => 'GA1.2.1926725822.1471014321',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/index.php',
    '__id' => 48,
];
Yii Framework
2016-10-10, 09:40:37

Apache/2.4.7 (Ubuntu)

**Comment by nathanverrill** [comment]
Can access site if you ignore the URL after login and change to soacha.evokenet.org

**Comment by JayantGandhi** [comment]
Should be fixed now - for some unknown reason the search plugin humhub uses got out of sync....rebuilding the indexes seemed to fix the issue
