### ISSUE TITLE
Could not create URL for content in firstwallentryid

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#204]
notification entry id 4414

<img width="640" alt="captura_de_pantalla_2016-10-10_a_las_9 44 37_a m" src="https://cloud.githubusercontent.com/assets/273429/19240545/84658c4c-8ed0-11e6-8d39-a4aba09ff864.png">

**Comment by JayantGandhi** [comment]
`{"name":"Exception","message":"Could not create url for content!","code":0,"type":"yii\\base\\Exception","file":"/home/ubuntu/humhub/protected/humhub/modules/content/models/Content.php","line":588,"stack-trace":["#0 /home/ubuntu/humhub/protected/humhub/modules/activity/components/BaseActivity.php(168): humhub\\modules\\content\\models\\Content->getUrl()","#1 /home/ubuntu/humhub/protected/humhub/modules/activity/components/BaseActivity.php(125): humhub\\modules\\activity\\components\\BaseActivity->getUrl()","#2 /home/ubuntu/humhub/protected/humhub/modules/content/activities/ContentCreated.php(43): humhub\\modules\\activity\\components\\BaseActivity->render('web', Array)","#3 /home/ubuntu/humhub/protected/humhub/modules/activity/models/Activity.php(96): humhub\\modules\\content\\activities\\ContentCreated->render()","#4 /home/ubuntu/humhub/protected/humhub/modules/content/components/actions/Stream.php(259): humhub\\modules\\activity\\models\\Activity->getWallOut()","#5 [internal function]: humhub\\modules\\content\\components\\actions\\Stream->run()","#6 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)","#7 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\\base\\Action->runWithParams(Array)","#8 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\\base\\Controller->runAction('stream', Array)","#9 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\\base\\Module->runAction('dashboard/dashb...', Array)","#10 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))","#11 /home/ubuntu/humhub/index.php(25): yii\\base\\Application->run()","#12 {main}"]}`

**Comment by JayantGandhi** [comment]
This error is happening in multiple places throughout the site...

**Comment by JayantGandhi** [comment]
It prevents the activity streams from loading (aka "Latest Activities")

**Comment by nathanverrill** [comment]
Does this still impact users, or is it hidden from view? I was looking at the logs on the site and it is still logged. Just want to make sure it isn't preventing players/mentors from submitting/reviewing, and they just aren't telling us about it. Evidence is still being posted, so it clearly isn't affecting everyone...

  Sun, 16 Oct 2016 11:03:25 -0500  yii\base\Exception
exception 'yii\base\Exception' with message 'Could not create url for content!' in /home/ubuntu/humhub/protected/humhub/modules/content/models/Content.php:588 Stack trace: #0 /home/ubuntu/humhub/protected/modules/missions/models/Votes.php(150): humhub\modules\content\models\Content->getUrl() #1 /home/ubuntu/humhub/protected/humhub/modules/content/models/Content.php(582): app\modules\missions\models\Votes->getUrl() #2 /home/ubuntu/humhub/protected/humhub/modules/notification/components/BaseNotification.php(238): humhub\modules\content\models\Content->getUrl() #3 /home/ubuntu/humhub/protected/humhub/modules/notification/controllers/EntryController.php(62): humhub\modules\notification\components\BaseNotification->getUrl() #4 [internal function]: humhub\modules\notification\controllers\EntryController->actionIndex() #5 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #6 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #7 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('', Array) #8 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('notification/en...', Array) #9 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #10 /home/ubuntu/humhub/index.php(25): yii\base\Application->run() #11 {main}

**Comment by nathanverrill** [comment]
this query fixed the evidence for players, but we still don't know why it occurs.

INSERT INTO wall_entry (wall_id,content_id,created_at,created_by,updated_at,updated_by) 

SELECT wa.id, c.id, e.created_at, e.created_by, e.updated_at, e.updated_by
from evidence e
left join content c on c.object_id = e.id
left join wall_entry w on w.content_id = c.id
left join wall wa on wa.object_id = c.space_id and wa.object_model = 'humhub\modules\space\models\Space'
where c.object_model = 'app\modules\missions\models\Evidence'
and isnull(wall_id)

**Comment by disheltCiti** [comment]
Hi!, I have the same problem, is there any update?
