### ISSUE TITLE
Error when trying to view reviews in admin

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#214]
went to admin on production, clicked reviews and got the following error

PHP Fatal Error – yii\base\ErrorException

Allowed memory size of 134217728 bytes exhausted (tried to allocate 3702784 bytes)
1. in /home/ubuntu/humhub/protected/modules/missions/views/admin/votes/index.php at line 40
31323334353637383940414243444546474849                <?php foreach ($reviews as $review): ?>
                    <tr>
                        <td><?php echo $review->user->username; ?></td>
                        <td>
                            <?php echo ($review->flag == 0) ? Yii::t('MissionsModule.base', 'No') : Yii::t('MissionsModule.base', 'Yes') ?>
                        </td>
                        <td><?php echo $review->value; ?></td>
                        <td>
                            <a class = "btn btn-success btn-sm" target="_blank" href="<?= Url::to(['/content/perma', 'id' => $review->evidence->getContentObject()->id]) ?>">
                                <?= Yii::t('MissionsModule.base', 'Jump to Post') ?>
                            </a>
                            &nbsp;&nbsp;
                            <?php echo Html::a(
                                Yii::t('MissionsModule.base', 'Delete'),
                                ['delete-reviews', 'id' => $review->id], array(
                                'class' => 'btn btn-danger btn-sm',
                                'data' => [
                                    'confirm' => Yii::t('MissionsModule.base', 'Are you sure you want to delete this review?'),
                                    'method' => 'post',
2. yii\base\ErrorHandler::handleFatalError()
$_GET = [
    'r' => 'missions/admin/index-reviews',
];

$_COOKIE = [
    '_csrf' => '016ab31f9bec3399ca748ef819e80f4df088cd8104d729681d3cb23584df57eea:2:{i:0;s:5:"_csrf";i:1;s:32:"6yFpFrcsRpCl8qdpLwmZtZOxoSWbOcc4";}',
    '_gat' => '1',
    'PHPSESSID' => '7lnricntcsusan5ju112iisna0',
    '_identity' => '59ae5cccac10c04bf5e1113b038afbe1d9553e85c93d4bef0e9d3699a3270fe1a:2:{i:0;s:9:"_identity";i:1;s:51:"[48,"73ec8dfe-93f3-406d-a15f-b86151b8bbff",2592000]";}',
    '_ga' => 'GA1.2.2102635792.1476713550',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/',
    '__id' => 48,
];
Yii Framework
2016-10-17, 09:14:50

Apache/2.4.7 (Ubuntu)
Yii Framework/2.0.7

**Comment by JayantGandhi** [comment]
My guess is that we're trying to pull too many reviews at one time (there are over 5000 now). Probably just a need for pagination
