### ISSUE TITLE
not receiving email notifications

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#218]
I checked to make sure I have the appropriate settings on my account. 

<img width="1145" alt="email-notifications" src="https://cloud.githubusercontent.com/assets/273429/19483122/dca63ac0-9518-11e6-9ab2-c0bdd61799df.png">

**Comment by Guihrmsfo** [comment]
These email notifications (review notification) were disabled for testing purposes 
(we're trying to verify if that's a possible cause for missing wall entry error).
Review's email notification is an Evoke's feature, when we able it again, you must check it on "Evoke Settings" tab.
