### ISSUE TITLE
Rubric not displayed with activity

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#22]
http://dev.humhub.m00.com.br/index.php?r=missions%2Fevidence%2Fshow&activityId=2&sguid=be05272f-8df8-4a9d-92fc-da6292ce5060

**Comment by Guihrmsfo** [comment]
Can't access it for some reason, maybe another bug? Is there any image for it, please?

**Comment by nathanverrill** [comment]
<img width="1097" alt="activity_rubric_missing_2" src="https://cloud.githubusercontent.com/assets/273429/16494268/4cdfd3c6-3eae-11e6-871f-65a898788532.png">
<img width="1167" alt="activity_rubric_missing" src="https://cloud.githubusercontent.com/assets/273429/16494269/4cf07456-3eae-11e6-896b-581287cf7455.png">

Happens in both English and Spanish, whether navigating there via evokation page or missions page. In the welcome space with user "Not an Admin"

**Comment by rjapur** [comment]
As this is content not provided and not a bug, should be removed and not closed.

**Comment by rjapur** [comment]
it's a content issue rather than a bug
