### ISSUE TITLE
page not found when navigating to evoke settings on player profile

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#226]
![image](https://cloud.githubusercontent.com/assets/273429/19520075/706b9028-95d4-11e6-8310-d6fe996cedf2.png)

Logged in as JonathanOlivera

**Comment by nathanverrill** [comment]
still occurs for all players
need to check email notification settings

**Comment by Guihrmsfo** [comment]
@nathanverrill 
Issue fixed.
"Enable Review Notification Emails" is disabled.
