### ISSUE TITLE
Evidence Submit: Error Message should be by form, not at top.

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#23]
If you leave a field blank when on the evidence submission form, the error message is at the top of the screen, instead of next to the form fields. 

<img width="1172" alt="error-should-be-by-field-not-top" src="https://cloud.githubusercontent.com/assets/273429/16491720/aab1d2a6-3ea4-11e6-992f-25892770a0d2.png">
<img width="738" alt="error-should-be-by-field" src="https://cloud.githubusercontent.com/assets/273429/16491722/aac461aa-3ea4-11e6-9082-f9cdf63ac597.png">

**Comment by Guihrmsfo** [comment]
Fixed.
