### ISSUE TITLE
Player reviews not displayed with their evidence even though header says they have a 4.2 average rating

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#236]
Player JonathanOlivera has 2 evidences with no reviews, although his profile header says he has an average rating of 4.2

http://soacha.evokenet.org/index.php?r=user%2Fprofile&uguid=546ddff4-ae24-45b8-852a-4420c7b05d91

This is a player who's evidence had the wall error that we resolved.

<img width="1159" alt="jo_header" src="https://cloud.githubusercontent.com/assets/273429/19534346/04ecd570-9609-11e6-95e4-72af9655fe24.png">

**Comment by nathanverrill** [comment]
User Johan Ocampo has the same issue and he too had evidence that was restored.

http://soacha.evokenet.org/index.php?r=user%2Fprofile&uguid=34d2efba-880c-4a71-b302-591790b974a7 has

**Comment by Guihrmsfo** [comment]
Player's average rating is working appropriately.
There are two other problems actually:
- The Evidence's Summary box isn't working (it's not showing any rating for agent's ratings)
- Some reviews don't have content, something to take a look either
