### ISSUE TITLE
Only evidence for andres2050h is displayed on the Uníon social team page

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#239]
This is the case for all users - team mates, admins and mentors

note that andres2050h was one of the players who had the wall entry id fix applied

**Comment by Guihrmsfo** [comment]
Are you sure? Can you give more details?
I can see all evidences with my admin user and as 'andres2050h'

**Comment by nathanverrill** [comment]
Had to wait a long time for the page to load from infinite scroll - the animation loading progress indicator wasn't displayed either. However, now it works. So something to keep in the back of our minds.
