### ISSUE TITLE
Social Group Uniminuto thinks an evidence is missing; appears to be an issue with Fredy Martinez on both dev and prod

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#241]
Social Group Uniminuto expects 18 evidences, sees 17
http://soacha.evokenet.org/index.php?r=space%2Fspace&sguid=436ce8e3-7509-4438-be14-53802146b3f7

Fredy Martinez
http://soacha.evokenet.org/index.php?r=user%2Fprofile&uguid=9837bad7-96f3-4af4-ac97-5e6123c16953

When I view one of the team members Fredy Martinez, the following error is logged:

INFO  Fri, 21 Oct 2016 08:58:53 -0500  application
$_GET = [ 'r' => 'missions/evidence/userfeed' 1 => '/missions/evidence/userfeed' 'limit' => '4' 'filters' => '' 'sort' => 'c' 'from' => '6314' 'mode' => 'normal' 'uguid' => '9837bad7-96f3-4af4-ac97-5e6123c16953' ] $_SERVER = [ 'HTTP_HOST' => 'soacha.evokenet.org' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_ACCEPT' => 'application/json, text/javascript, _/_; q=0.01' 'HTTP_X_CSRF_TOKEN' => 'S1VpUmROQUJ9LC8iIjwiMRklKj5cPyUyByIECBAUDjokBj4wKy0idg==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36' 'HTTP_REFERER' => 'http://soacha.evokenet.org/index.php?r=user%2Fprofile&uguid=9837bad7-96f3-4af4-ac97-5e6123c16953' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,es;q=0.6' 'HTTP_COOKIE' => '_csrf=016ab31f9bec3399ca748ef819e80f4df088cd8104d729681d3cb23584df57eea%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%226yFpFrcsRpCl8qdpLwmZtZOxoSWbOcc4%22%3B%7D; pm_groups-statistics-panel=expanded; pm_space-members-panel=expanded; pm_new-spaces-panel=expanded; pm_user-spaces-panel=expanded; pm_profile-following-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_profile-follower-panel=expanded; language=2e2c7fa0242766f45a734a15a20a634d37b58d606f6f05f0aad08c2640adbbeea%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22es%22%3B%7D; PHPSESSID=knil1980ibl6u77e8bdj761pk2; _gat=1; _ga=GA1.2.2102635792.1476713550; _identity=59ae5cccac10c04bf5e1113b038afbe1d9553e85c93d4bef0e9d3699a3270fe1a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A51%3A%22%5B48%2C%2273ec8dfe-93f3-406d-a15f-b86151b8bbff%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at soacha.evokenet.org Port 80</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)' 'SERVER_NAME' => 'soacha.evokenet.org' 'SERVER_ADDR' => '172.31.18.75' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '97.91.238.101' 'DOCUMENT_ROOT' => '/var/www/html/humhub' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/html/humhub' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/var/www/html/humhub/index.php' 'REMOTE_PORT' => '57579' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=missions%2Fevidence%2Fuserfeed&1=%2Fmissions%2Fevidence%2Fuserfeed&limit=4&filters=&sort=c&from=6314&mode=normal&uguid=9837bad7-96f3-4af4-ac97-5e6123c16953' 'REQUEST_URI' => '/index.php?r=missions%2Fevidence%2Fuserfeed&1=%2Fmissions%2Fevidence%2Fuserfeed&limit=4&filters=&sort=c&from=6314&mode=normal&uguid=9837bad7-96f3-4af4-ac97-5e6123c16953' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1477058333.736 'REQUEST_TIME' => 1477058333 ]

WARNING  Fri, 21 Oct 2016 08:58:54 -0500  application
Syntax error.

This occurs on both Prod and Dev. On dev however it only occurs on Fredy's profile and not the team's. Here's the error on dev:

$_GET = [ 'r' => 'missions/evidence/userfeed' 1 => '/missions/evidence/userfeed' 'limit' => '4' 'filters' => '' 'sort' => 'c' 'from' => '5532' 'mode' => 'normal' 'uguid' => '9837bad7-96f3-4af4-ac97-5e6123c16953' ] $_SERVER = [ 'HTTP_HOST' => 'dev.humhub.m00.com.br' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_ACCEPT' => 'application/json, text/javascript, _/_; q=0.01' 'HTTP_X_CSRF_TOKEN' => 'TTJtcURFOGQSAhQALDJ8EgZLDgBzNQooCH8sSHd2QAcgex8TDAhpBg==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36' 'HTTP_REFERER' => 'http://dev.humhub.m00.com.br/index.php?r=user%2Fprofile&uguid=9837bad7-96f3-4af4-ac97-5e6123c16953' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,es;q=0.6' 'HTTP_COOKIE' => '_csrf=ba700166b0b98db171787a000d72059e746ae910dc273d11659a023bca91e536a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22_0yqhwDvKycq7p2LEMA933xcmIrbHMQb%22%3B%7D; pm_space-members-panel=expanded; pm_user-spaces-panel=expanded; pm_profile-following-panel=expanded; pm_groups-statistics-panel=expanded; pm_profile-follower-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_new-spaces-panel=expanded; _gat=1; language=21351261ae4d81ca3f5873a42e399a283387c65465209c43ef5571abea4dc6c1a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22es%22%3B%7D; PHPSESSID=4tc2mnvan1ddnkfoa1gn45qa12; _ga=GA1.3.2002704219.1476726594; _identity=18135249c15fa6b3c232e37abfaaa1f933b835510c0ecbfbf3d25b25e1fdd92ba%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A51%3A%22%5B48%2C%2273ec8dfe-93f3-406d-a15f-b86151b8bbff%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '' 'SERVER_SOFTWARE' => 'Apache' 'SERVER_NAME' => 'dev.humhub.m00.com.br' 'SERVER_ADDR' => '45.55.160.126' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '97.91.238.101' 'DOCUMENT_ROOT' => '/srv/www/dev.humhub.m00.com.br' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/srv/www/dev.humhub.m00.com.br' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/srv/www/dev.humhub.m00.com.br/index.php' 'REMOTE_PORT' => '57958' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=missions%2Fevidence%2Fuserfeed&1=%2Fmissions%2Fevidence%2Fuserfeed&limit=4&filters=&sort=c&from=5532&mode=normal&uguid=9837bad7-96f3-4af4-ac97-5e6123c16953' 'REQUEST_URI' => '/index.php?r=missions%2Fevidence%2Fuserfeed&1=%2Fmissions%2Fevidence%2Fuserfeed&limit=4&filters=&sort=c&from=5532&mode=normal&uguid=9837bad7-96f3-4af4-ac97-5e6123c16953' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1477058947.794 'REQUEST_TIME' => 1477058947 ]

**Comment by Guihrmsfo** [comment]
Looking on database, there are only 17 evidences for this team. Why do they expect 18?

**Comment by nathanverrill** [comment]
Going to have Roxana see if it's perception and which activity/user they think is missing.

**Comment by nathanverrill** [comment]
So gonna close for now.

**Comment by nathanverrill** [comment]
I'm sure since they're required to complete these for school they know what
they have done and not done. Any idea on Fredy?
