### ISSUE TITLE
Image Previews In Status Posts Only, Not in Evidences

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#242]
When a student uploads photos for an evidence, it is only displayed in the stream as an attachment.

It should have an image preview in the stream, like it does when they post a status update.

To recreate:
- Submit an evidence with the attached image. It only shows as an attachment.
- Submit a status update at the top of the team stream, and attach the same image. The image appears in the stream.

This makes it difficult to scan evidences. Did this used to work?

![ejercicio 1_pi_200x200](https://cloud.githubusercontent.com/assets/273429/19621355/9a19e14e-9855-11e6-9203-fd8b0f2f93fb.jpg)

**Comment by nathanverrill** [comment]
This occurs on the dashboard stream when viewing the site as a mentor, on the player profile stream, but not on the review evidence page.

**Comment by nathanverrill** [comment]
@rjapur @Guihrmsfo would you mind describing why this is not easy to fix? I'd like to be able to consider other approaches we might use from a UX perspective.

**Comment by rjapur** [comment]
Lucas answered our question and we fixed it, we've deployed it on dev last Friday
