### ISSUE TITLE
Evidence Review: Review widget not always displayed

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#27]
In some instances the review widget is not displayed and I can't tell why. 

I was logged in as the user with first name Alchemy

<img width="952" alt="no_review_widget" src="https://cloud.githubusercontent.com/assets/273429/16546920/bdb132e8-411f-11e6-811e-7d8323f09329.png">

**Comment by nathanverrill** [comment]
Perhaps it is because this user is a member of multiple teams.

**Comment by Guihrmsfo** [comment]
Yes, you can't review it because it's your own evidence since this member is a member of multiple teams.
