### ISSUE TITLE
Dev: "Page not work" when I click on notification for receiving "quality review" notification

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#278]
1. login as mentor
2. leave a review on an evidence you'll be able to easily find when logged in as admin
3. logout and login as an admin
4. return to the evidence and mark it as a quality review
5. logout and login as the mentor who received the quality review
6. click on notification for unlocking quality review achievement
7. click notification, get "page not working" error
8. Expected result is to go to their achievement page

http://dev.humhub.m00.com.br/index.php?r=notification%2Fentry&id=5532#

<img width="1208" alt="page-not-working" src="https://cloud.githubusercontent.com/assets/273429/20062264/b41aa342-a4c8-11e6-877a-c3317499ef51.png">

**Comment by Guihrmsfo** [comment]
Same as #293.

**Comment by nathanverrill** [comment]
closing since this is a dupe
