### ISSUE TITLE
After removing an evokation from my portfolio, I can no longer add additional evokations to my portfolio

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#284]
- Add an Evokation to portfolio
- Use the spinner to go down to zero
- Click save
- scroll down to other evokations and click invest, it just refreshes the page
- refresh the page again, to see if that will make it work, and invest in evokations still does not work

**Comment by Guihrmsfo** [comment]
It seems it was a wrong character in an evokation title.
I removed that evokation and now it's working on dev. 
I'll replicate on my local and develop some prevention for that error, please don't close this issue yet.

**Comment by nathanverrill** [comment]
What was the wrong character?

Note one of the scenarios I used was copy/pasting from a google doc.

**Comment by Guihrmsfo** [comment]
I'm not sure, but I suppose it was a new line character
