### ISSUE TITLE
clicking "marked quality review" notification goes to "page not working"

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#293]
As an admin, I marked a comment by lobo plateado
http://dev.humhub.m00.com.br/index.php?r=user%2Fprofile&uguid=1f21af45-f0b3-4c40-9f89-7c9a81c76055

Evidence
http://dev.humhub.m00.com.br/index.php?r=space%2Fspace&wallEntryId=6742&sguid=a707657a-fce4-44b9-b1e5-749ea45d4083

I logged in as lobo plateado, and clicked his notification in the top notifications and went to this page
http://dev.humhub.m00.com.br/index.php?r=notification%2Fentry&id=5554#

Which says "page not working"

**Comment by nathanverrill** [comment]
A notification is not being sent to the person whose review was marked as a quality review

**Comment by nathanverrill** [comment]
See the error logs on dev; I flushed them before beginning my QA.

**Comment by Guihrmsfo** [comment]
It's an achievement notification, if the user has previously gained that achievement, he shouldn't receive another notification.

**Comment by nathanverrill** [comment]
Okay - usability wise I would expect to receive a notification whenever I have one of my reviews recognized by the admin as quality, and click a link to the evidence where my comment is so o can see which one   

 Sent from my walkie talkie

   This (https://itunes.apple.com/app/apple-store/id922793622?pt=814382&mt=8&ct=how_i_email)  is how I Email now
