### ISSUE TITLE
reviews not displayed with evidence

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#294]
logged in as logo plateado, i clicked on the quality reviews on his profile page and went to this page

http://dev.humhub.m00.com.br/index.php?r=space%2Fspace&wallEntryId=6742&sguid=a707657a-fce4-44b9-b1e5-749ea45d4083

And no reviews are displayed

**Comment by Guihrmsfo** [comment]
No reviews are displayed 'cause as previously specified, users can't see reviews unless they are the evidence author.

**Comment by nathanverrill** [comment]
reviews should always be displayed with evidence, just the review authors are anonymized when viewed by a player, as opposed to a mentor or an admin when the player names are visible.

also, I corrected the title
