### ISSUE TITLE
Prod: Multiple users are getting a server error when trying to review evidence

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#306]
Users tested who had the error:
Angie Morales
GerardoMonzon
fredy martinez
roberto

Users who don't have the error
Natalia Medina

**Comment by Guihrmsfo** [comment]
Which error?

**Comment by nathanverrill** [comment]
This was addressed on production, @JayantGandhi to update with notes on how to fix for posterity

**Comment by JayantGandhi** [comment]
It was a permissions error on the uploads/file folder. You have to ensure that both read and write privileges are granted to `www-data` both as the owner and the group (on the production server it was only the group, not the owner which was causing the issue).
