### ISSUE TITLE
review saved twice (happened only once)

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#318]
1. navigate to an evidence
2. enter a review
3. edit it, save
4. view the evidence as another user

![image](https://cloud.githubusercontent.com/assets/273429/20188633/25d3bf0a-a73f-11e6-8190-e65867027ed9.png)

**Comment by nathanverrill** [comment]
this doesn't occur in the dashboard stream, only on the stream for the team or user profile

User: Mentor Nathan Verrill
Evidence:
http://dev.humhub.m00.com.br/index.php?r=content%2Fperma&id=10434

Evidence Author:
http://dev.humhub.m00.com.br/index.php?r=user%2Fprofile&uguid=935610e8-1db0-4925-a481-afc2488f11c1

Evidence Author's Team
http://dev.humhub.m00.com.br/index.php?r=space%2Fspace&sguid=40f61858-fa42-4177-9634-580f04f8c445

**Comment by Guihrmsfo** [comment]
@nathanverrill 
Is that happening everytime? The bug isn't the displaying, but the duplicated review.
(There are two votes from Nathan to the same evidence)
I tried to replicate, but failed.

**Comment by nathanverrill** [comment]
something to keep an eye on, unable to recreate
