### ISSUE TITLE
Evidences in Team Header, 44 when No Evidences

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#32]
Create a new team, don't submit any evidences; team header says there are 44

<img width="1189" alt="44_evidences" src="https://cloud.githubusercontent.com/assets/273429/16881512/961014c6-4a88-11e6-8b3f-edd164659dd1.png">

**Comment by nathanverrill** [comment]
After I submit an evidence, it shows 45 evidences. Is it showing total evidences on the platform, or only those on my team?

**Comment by Guihrmsfo** [comment]
Database issue also, fixed.
