### ISSUE TITLE
Team Status Update Doesn't show up in main stream under update box

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#33]
Create a new user
Navigate to welcome space (now called base of operations for soacha)
Enter a status update
Status update indicator for stream (the moving dots) never stops and the status update never appears
The status update does appear in the activity stream in the sidebar

<img width="1173" alt="no_status" src="https://cloud.githubusercontent.com/assets/273429/16881943/94c34f46-4a8a-11e6-81f6-d17b07b84451.png">

**Comment by Guihrmsfo** [comment]
It was just a database bug, it's working appropriately now.
