### ISSUE TITLE
spinners don't work to adjust investment

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#331]
On OSX/Chrome, using the up/down spinners doesn't change the value. Ideally we don't have the spinners at all.

<img width="906" alt="spinners-no-work" src="https://cloud.githubusercontent.com/assets/273429/20280609/cc5ace5a-aa72-11e6-9691-8ed6f8b4ec3c.png">

**Comment by nathanverrill** [comment]
No longer working. the following two solutions are acceptable: not having them and no visual indicator, or functioning

**Comment by nathanverrill** [comment]
Also don't lend themselves to mobile(hard to distinguish between arrows and trashcan) - so suggest removing them or hiding them visually if there is javascript changes that might introduce issues.

**Comment by Guihrmsfo** [comment]
It's working on dev for me. 
How can I replicate it?

**Comment by nathanverrill** [comment]
I suggest just removing them

**Comment by nathanverrill** [comment]
In answer to your question, I'm on Mac/Safari and I use a standard process - log in as a player, add an elevator pitch to my portfolio, and try and use the spinners. First with just 1 item in the portfolio, then with multiple.

**Comment by Guihrmsfo** [comment]
Ok, I think I'll remove it then. It'd be simpler if we don't use js on dynamic elements until we figure it out the rendering javascript issue we have.

**Comment by nathanverrill** [comment]
After spinners were removed, they appeared again when a second evokation was added.
