### ISSUE TITLE
Player can review their own evidence (should not be able to)

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#34]
To recreate, create just one evidence on the platform, and go to review evidence as the player who submitted the evidence. The player's own evidence is displayed for voting.

<img width="1191" alt="review_own_evidence" src="https://cloud.githubusercontent.com/assets/273429/16882325/756d4cee-4a8c-11e6-80e9-9499fb4c0b16.png">

**Comment by Guihrmsfo** [comment]
Is the user a member of multiple teams? (includes mentors and welcome space)

**Comment by Guihrmsfo** [comment]
New feature prevents this bug.
