### ISSUE TITLE
Error when signing up w/ email address

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#346]
To recreate go to home page and enter an email address to sign up. Following error occurs:

exception 'Swift_TransportException' with message 'Expected response code 250 but got code "554", with message "554 Message rejected: Sending suspended for this account. For more information, please check the inbox of the email address associated with your AWS account. "' in /home/ubuntu/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383 Stack trace: #0 /home/ubuntu/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('554 Message rej...', Array) #1 /home/ubuntu/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(243): Swift_Transport_AbstractSmtpTransport->executeCommand('??.??', Array, Array) #2 /home/ubuntu/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(333): Swift_Transport_EsmtpTransport->executeCommand('??.??', Array) #3 /home/ubuntu/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(428): Swift_Transport_AbstractSmtpTransport->_streamMessage(Object(Swift_Message)) #4 /home/ubuntu/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(444): Swift_Transport_AbstractSmtpTransport->_doMailTransaction(Object(Swift_Message), 'no-reply@quanti...', Array, Array) #5 /home/ubuntu/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(176): Swift_Transport_AbstractSmtpTransport->_sendTo(Object(Swift_Message), 'no-reply@quanti...', Array, Array) #6 /home/ubuntu/humhub/protected/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array) #7 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2-swiftmailer/Mailer.php(146): Swift_Mailer->send(Object(Swift_Message)) #8 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/mail/BaseMailer.php(260): yii\swiftmailer\Mailer->sendMessage(Object(yii\swiftmailer\Message)) #9 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/mail/BaseMessage.php(48): yii\mail\BaseMailer->send(Object(yii\swiftmailer\Message)) #10 /home/ubuntu/humhub/protected/humhub/modules/user/models/Invite.php(109): yii\mail\BaseMessage->send() #11 /home/ubuntu/humhub/protected/humhub/modules/user/controllers/AuthController.php(82): humhub\modules\user\models\Invite->sendInviteMail() #12 [internal function]: humhub\modules\user\controllers\AuthController->actionLogin() #13 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #14 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #15 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('login', Array) #16 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('user/auth/login', Array) #17 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #18 /home/ubuntu/humhub/index.php(23): yii\base\Application->run() #19 {main}

**Comment by rjapur** [comment]
Already fixed.

**Comment by JayantGandhi** [comment]
Actually fixed now
