### ISSUE TITLE
Material UI

### ISSUE THREAD

**Issue by JayantGandhi** [EvokeNet/humhub#349]
Attempt to integrate some material design into the site

**Comment by nathanverrill** [comment]
Graphic Novel Pages not appearing even though they are loaded in the admin

**Comment by nathanverrill** [comment]
Top Navigation wraps on some pages and the dashboard controls are on the sidebar and squooshed

<img width="1161" alt="design-tweaks" src="https://cloud.githubusercontent.com/assets/273429/21815310/be72f9f8-d721-11e6-8f77-a8965709d2bb.png">
