### ISSUE TITLE
Missions Unavailable to New Team

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#403]
After creating a new user with the admin panel, logging in as them, and adding a team, the missions were not visible.

**Comment by nathanverrill** [comment]
Update: this is only when it is using a user that is created in the admin. I tried again after "creating wallets" before becoming the user and had the same issue.

**Comment by Guihrmsfo** [comment]
Which user? Could post some prints? I failed to replicate.

**Comment by nathanverrill** [comment]
This is because I forgot we need to use the create team link on the dashboard call to action instead of create space. When I create the teams w/ the dashboard call to action it works A-OK.
