### ISSUE TITLE
Error After Completing Survey

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#419]
PHP Notice – yii\base\ErrorException

Trying to get property of non-object
1. in /home/ubuntu/humhub/protected/modules/matching_questions/views/matching-questions/matching-results.php at line 128
119120121122123124125126127128129130131132133134135136137 
                  <br>
 
                  <p style = "margin-bottom:10px"><?php echo Yii::t('MatchingModule.base', '{agent}: Congratulations, you are already an Evoke agent!', array('agent' => $user->username)) ?></p>
 
                  <br>
                  <?php if(Setting::Get('novel_order') == EvokeSettingsForm::FIRST_NOVEL): ?>
                      <div class = "text-center"><?php echo Html::a(
                          Yii::t('MatchingModule.base', 'Continue to Base Operations'),
                          ['/space/space', 'sguid' => $welcome_space->guid], array('class' => 'btn btn-cta1')); ?></div>
                  <?php else: ?>
                      <div class = "text-center"><?php echo Html::a(
                          Yii::t('MatchingModule.base', 'Continue to Novel'),
                          ['/novel/novel/graphic-novel', 'page' => 1], array('class' => 'btn btn-cta1')); ?></div>
                  <?php endif; ?>
                  <br>
                </div>
 
              </div>
2. in /home/ubuntu/humhub/protected/modules/matching_questions/views/matching-questions/matching-results.php at line 128 – yii\base\ErrorHandler::handleError(8, 'Trying to get property of non-ob...', '/home/ubuntu/humhub/protected/mo...', 128, ...)
122123124125126127128129130131132133134                  <p style = "margin-bottom:10px"><?php echo Yii::t('MatchingModule.base', '{agent}: Congratulations, you are already an Evoke agent!', array('agent' => $user->username)) ?></p>
 
                  <br>
                  <?php if(Setting::Get('novel_order') == EvokeSettingsForm::FIRST_NOVEL): ?>
                      <div class = "text-center"><?php echo Html::a(
                          Yii::t('MatchingModule.base', 'Continue to Base Operations'),
                          ['/space/space', 'sguid' => $welcome_space->guid], array('class' => 'btn btn-cta1')); ?></div>
                  <?php else: ?>
                      <div class = "text-center"><?php echo Html::a(
                          Yii::t('MatchingModule.base', 'Continue to Novel'),
                          ['/novel/novel/graphic-novel', 'page' => 1], array('class' => 'btn btn-cta1')); ?></div>
                  <?php endif; ?>
                  <br>
3. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/home/ubuntu/humhub/protected/mo...')
4. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/home/ubuntu/humhub/protected/mo...', ['quality_1' => app\modules\matching_questions\models\Qualities, 'quality_2' => app\modules\matching_questions\models\Qualities, 'superhero_identity' => app\modules\matching_questions\models\SuperheroIdentities, 'relevant_powers' => [app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers], ...])
5. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/home/ubuntu/humhub/protected/mo...', ['quality_1' => app\modules\matching_questions\models\Qualities, 'quality_2' => app\modules\matching_questions\models\Qualities, 'superhero_identity' => app\modules\matching_questions\models\SuperheroIdentities, 'relevant_powers' => [app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers], ...], app\modules\matching_questions\controllers\MatchingQuestionsController)
6. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 377 – yii\base\View::render('matching-results', ['quality_1' => app\modules\matching_questions\models\Qualities, 'quality_2' => app\modules\matching_questions\models\Qualities, 'superhero_identity' => app\modules\matching_questions\models\SuperheroIdentities, 'relevant_powers' => [app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers], ...], app\modules\matching_questions\controllers\MatchingQuestionsController)
7. in /home/ubuntu/humhub/protected/modules/matching_questions/controllers/MatchingQuestionsController.php at line 196 – yii\base\Controller::render('matching-results', ['quality_1' => app\modules\matching_questions\models\Qualities, 'quality_2' => app\modules\matching_questions\models\Qualities, 'superhero_identity' => app\modules\matching_questions\models\SuperheroIdentities, 'relevant_powers' => [app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers, app\modules\powers\models\UserPowers], ...])
190191192193194195196197198199200201202            }
 
            $other_qualities = Qualities::find()->where(['not in', 'id', $quality_1->id])->all();
 
            $welcome_space = Space::find()->where(['id' => 1])->one();
 
            return $this->render('matching-results', compact('quality_1', 'quality_2', 'superhero_identity', 'relevant_powers', 'other_qualities', 'super_powers', 'welcome_space'));
 
        } else{
            return $this->redirectQuestionnaire();
        }
    }
 
8. app\modules\matching_questions\controllers\MatchingQuestionsController::actionMatching()
9. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([app\modules\matching_questions\controllers\MatchingQuestionsController, 'actionMatching'], [])
10. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'matching_questions/matching-ques...'])
11. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('matching', ['r' => 'matching_questions/matching-ques...'])
12. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('matching_questions/matching-ques...', ['r' => 'matching_questions/matching-ques...'])
13. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
14. in /home/ubuntu/humhub/index.php at line 25 – yii\base\Application::run()
19202122232425    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'matching_questions/matching-questions/matching',
];

$_POST = [
    '_csrf' => 'WU9YcHZzeGccAG1FQgInEXQdPUlCGykdbyMTBScdPABrNSs/PgNBCQ==',
    'matching_answer_13_matching_question_4' => '2',
    'matching_answer_14_matching_question_4' => '1',
    'matching_answer_15_matching_question_4' => '4',
    'matching_answer_16_matching_question_4' => '3',
    'matching_answer_17_matching_question_5' => '4',
    'matching_answer_18_matching_question_5' => '1',
    'matching_answer_19_matching_question_5' => '3',
    'matching_answer_20_matching_question_5' => '2',
    'matching_question_6' => '1',
    'matching_question_7' => '4',
    'matching_question_8' => '5',
    'matching_question_9' => '7',
    'matching_question_10' => '9',
    'matching_question_11' => '11',
];

$_COOKIE = [
    'fs_uid' => 'www.fullstory.com`21CH0`5649391675244544:5652720409116672',
    '_csrf' => '0f6daa3ff6243b133d9939aba15720f57973e8e33f0278934f29cd7f02022b66a:2:{i:0;s:5:"_csrf";i:1;s:32:"EO554q_v-Re94hQz6lKuQnDg2zsOHp9n";}',
    'pm_space-members-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'pm_groups-statistics-panel' => 'expanded',
    'pm_new-spaces-panel' => 'expanded',
    '_gat' => '1',
    'language' => '9af3597d700b1e74cb505508460e6f1f74ffdf917785b0817ba7ed34f85c4562a:2:{i:0;s:8:"language";i:1;s:2:"en";}',
    'PHPSESSID' => 'q612c9va5p8pausf10df6a2cl2',
    '_ga' => 'GA1.2.1211353109.1477168503',
    '_identity' => '17394f3b19bde0ab7618c831b9f36df94e1278249e997cf632261b215c66607ca:2:{i:0;s:9:"_identity";i:1;s:52:"[247,"2c9ccd99-a998-4ded-8159-2ac9d853b7d8",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/index.php',
    '__captcha/user/auth/captcha' => 'rufiyas',
    '__captcha/user/auth/captchacount' => 1,
    '__id' => 247,
];
Yii Framework
2017-02-06, 11:51:26

Apache/2.4.7 (Ubuntu)
Yii Framework/2.0.7

**Comment by Guihrmsfo** [comment]
Which server that happened?

**Comment by JayantGandhi** [comment]
@nathanverrill can you double check now? Might have been the same issue as the other novel bug.

**Comment by JayantGandhi** [comment]
Figured out what's causing it....

The space id in the matching questions controller for what the welcome space is was hardcoded.

This doesn't correspond to what it is on the literacy site, hence the error.

I'm going to quickly fix it in the literacy database for now, but we should address this at some point and un-hardcode it.
