### ISSUE TITLE
Error when trying to review the novel

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#421]
Click on novel in the top navigation

http://literacy.evokenet.org/index.php?r=novel%2Fnovel%2Fgraphic-novel&page=1

Unknown Property – yii\base\UnknownPropertyException

Getting unknown property: app\modules\novel\models\NovelPage::markup
1. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Component.php at line 143
134135136137138139140141142143144145146147148149150151152            foreach ($this->_behaviors as $behavior) {
                if ($behavior->canGetProperty($name)) {
                    return $behavior->$name;
                }
            }
        }
        if (method_exists($this, 'set' . $name)) {
            throw new InvalidCallException('Getting write-only property: ' . get_class($this) . '::' . $name);
        } else {
            throw new UnknownPropertyException('Getting unknown property: ' . get_class($this) . '::' . $name);
        }
    }
 
    /**
     * Sets the value of a component property.
     * This method will check in the following order and act accordingly:
     *
     *  - a property defined by a setter: set the property value
     *  - an event in the format of "on xyz": attach the handler to the event "xyz"
2. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 247 – yii\base\Component::__get('markup')
3. in /home/ubuntu/humhub/protected/modules/novel/views/novel/novel/page.php at line 13 – yii\db\BaseActiveRecord::__get('markup')
78910111213141516171819?>
<style media="screen">
 
  .graphic-novel-page{
    min-height:200vh;
 
    <?php if($page->markup != ""): ?>
    <?php else: ?>
    background-image:url('<?= $page->page_image ?>');
    <?php endif; ?>
 
    background-size:contain;
    background-repeat:no-repeat;
4. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/home/ubuntu/humhub/protected/mo...')
5. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/home/ubuntu/humhub/protected/mo...', ['page' => app\modules\novel\models\NovelPage])
6. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/home/ubuntu/humhub/protected/mo...', ['page' => app\modules\novel\models\NovelPage], humhub\modules\novel\controllers\NovelController)
7. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 377 – yii\base\View::render('novel/page', ['page' => app\modules\novel\models\NovelPage], humhub\modules\novel\controllers\NovelController)
8. in /home/ubuntu/humhub/protected/modules/novel/controllers/NovelController.php at line 68 – yii\base\Controller::render('novel/page', ['page' => app\modules\novel\models\NovelPage])
62636465666768697071727374          $user->has_read_novel = true;
          $user->save();
          return $this->redirect(['/']);
        }
      }
 
      return $this->render('novel/page', array('page' => $page));
    }
 
    public function actionTransformation()
    {
      $user = Yii::$app->user->getIdentity();
      MatchingQuestionsController::setInitialPowers();
9. humhub\modules\novel\controllers\NovelController::actionGraphicNovel('1')
10. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\novel\controllers\NovelController, 'actionGraphicNovel'], ['1'])
11. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'novel/novel/graphic-novel', 'page' => '1'])
12. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('graphic-novel', ['r' => 'novel/novel/graphic-novel', 'page' => '1'])
13. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('novel/novel/graphic-novel', ['r' => 'novel/novel/graphic-novel', 'page' => '1'])
14. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
15. in /home/ubuntu/humhub/index.php at line 25 – yii\base\Application::run()
19202122232425    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'novel/novel/graphic-novel',
    'page' => '1',
];

$_COOKIE = [
    'fs_uid' => 'www.fullstory.com`21CH0`5649391675244544:5652720409116672',
    '_csrf' => '0f6daa3ff6243b133d9939aba15720f57973e8e33f0278934f29cd7f02022b66a:2:{i:0;s:5:"_csrf";i:1;s:32:"EO554q_v-Re94hQz6lKuQnDg2zsOHp9n";}',
    'pm_space-members-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'pm_groups-statistics-panel' => 'expanded',
    'pm_new-spaces-panel' => 'expanded',
    'language' => '9af3597d700b1e74cb505508460e6f1f74ffdf917785b0817ba7ed34f85c4562a:2:{i:0;s:8:"language";i:1;s:2:"en";}',
    '_gat' => '1',
    'PHPSESSID' => '1puhfkj2g858hbuskrqk8a3dm6',
    '_ga' => 'GA1.2.1211353109.1477168503',
    '_identity' => 'd6d341b77f54e53022cf4f94e2edfecb937cb2fca6757a886585d737cd6bc1cba:2:{i:0;s:9:"_identity";i:1;s:52:"[241,"d341a0cd-fa88-44d8-8653-d88369c26789",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/index.php',
    '__id' => 247,
];
Yii Framework
2017-02-06, 13:16:24

Apache/2.4.7 (Ubuntu)
Yii Framework/2.0.7

**Comment by Guihrmsfo** [comment]
It's working on dev for me, which user you're logged in?

**Comment by JayantGandhi** [comment]
Fixed, it was my bad, forgot to migrate after the update.
