### ISSUE TITLE
Earn when viewing base of operations members

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#43]
To recreate, go to base of operations as an admin, hit the gear and choose members. The following error occurs:

PHP Notice – yii\base\ErrorException

Trying to get property of non-object
1. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/space/modules/manage/views/member/index.php at line 35
26272829303132333435363738394041424344                    'user.username',
                    'user.profile.firstname',
                    'user.profile.lastname',
                    [
                        'label' => Yii::t('SpaceModule.views_admin_members', 'Group'),
                        'class' => 'humhub\libs\DropDownGridColumn',
                        'attribute' => 'group_id',
                        'submitAttributes' => ['user_id'],
                        'readonly' => function ($data) use ($space) {
                    if ($space->isSpaceOwner($data->user->id)) {
                        return true;
                    }
                    return false;
                },
                        'filter' => $groups,
                        'dropDownOptions' => $groups,
                        'value' =>
                        function ($data) use (&$groups, $space) {
                    return $groups[$data->group_id];
2. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/space/modules/manage/views/member/index.php at line 35 – yii\base\ErrorHandler::handleError(8, 'Trying to get property of non-ob...', '/srv/www/dev.humhub.m00.com.br/p...', 35, ...)

**Comment by Guihrmsfo** [comment]
Database issue.
Relation between an inexistent user and a space.
Fixed.
