### ISSUE TITLE
Incorrect mission order on Literacy site despite setting "position" property

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#437]
Position property is set for missions 1-8, but they are listed 1-4, 6-8, then 5

Occurs in both admin and on the missions page.

** Don't address until after demo---just in case.

**Comment by nathanverrill** [comment]
note that on Literacy I changed the names & codes for the missions so it "looks" like they are in order for demo purposes, so it will look like the ordering is working properly.

**Comment by nathanverrill** [comment]
what was the issue?

**Comment by Guihrmsfo** [comment]
The query missed an 'order by'
