### ISSUE TITLE
Stream not loading on Literacy

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#438]
Logged in as Mentor Bob Hawkins and followed three teams.

Went to "home" dashboard, and activity stream never loaded.

the following information was logged:

$_GET = [ 'r' => 'missions/dashboard/stream' 'limit' => '4' 'filters' => '' 'sort' => 'c' 'from' => '' 'mode' => 'normal' ] $_SERVER = [ 'HTTP_HOST' => 'literacy.evokenet.org' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_X_CSRF_TOKEN' => 'N3NYcG5fR3FyPG1FWi4YBxohPUlaNxYLAR8TBT8xAxYFCSs/Ji9.Hw==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' 'HTTP_REFERER' => 'http://literacy.evokenet.org/index.php?r=dashboard%2Fdashboard' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,es;q=0.6' 'HTTP_COOKIE' => 'fs_uid=www.fullstory.com`21CH0`5649391675244544:5652720409116672; _csrf=0f6daa3ff6243b133d9939aba15720f57973e8e33f0278934f29cd7f02022b66a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22EO554q_v-Re94hQz6lKuQnDg2zsOHp9n%22%3B%7D; pm_space-members-panel=expanded; pm_user-spaces-panel=expanded; pm_groups-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_user-tags-panel=expanded; language=9af3597d700b1e74cb505508460e6f1f74ffdf917785b0817ba7ed34f85c4562a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; _gat=1; PHPSESSID=oif2pjaib1bfgl2g83obcfkp77; _ga=GA1.2.1211353109.1477168503; _identity=d6d341b77f54e53022cf4f94e2edfecb937cb2fca6757a886585d737cd6bc1cba%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A52%3A%22%5B241%2C%22d341a0cd-fa88-44d8-8653-d88369c26789%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at literacy.evokenet.org Port 80</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)' 'SERVER_NAME' => 'literacy.evokenet.org' 'SERVER_ADDR' => '172.31.32.11' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '97.88.214.229' 'DOCUMENT_ROOT' => '/var/www/html/humhub' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/html/humhub' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/var/www/html/humhub/index.php' 'REMOTE_PORT' => '55677' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=missions%2Fdashboard%2Fstream&limit=4&filters=&sort=c&from=&mode=normal' 'REQUEST_URI' => '/index.php?r=missions%2Fdashboard%2Fstream&limit=4&filters=&sort=c&from=&mode=normal' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1486477259.802 'REQUEST_TIME' => 1486477259 ]
ERROR  Tue, 07 Feb 2017 09:21:00 -0500  yii\base\ErrorException:8
exception 'yii\base\ErrorException' with message 'Undefined offset: 0' in /home/ubuntu/humhub/protected/modules/missions/widgets/views/mentor_review.php:38 Stack trace: #0 /home/ubuntu/humhub/protected/modules/missions/widgets/views/mentor_review.php(38): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/home/ubuntu/hu...', 38, Array) #1 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(325): require('/home/ubuntu/hu...') #2 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/ubuntu/hu...', Array) #3 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/ubuntu/hu...', Array, NULL) #4 /home/ubuntu/humhub/protected/modules/missions/widgets/views/entry.php(142): yii\base\View->render('mentor_review', Array) #5 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(325): require('/home/ubuntu/hu...') #6 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/ubuntu/hu...', Array) #7 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/ubuntu/hu...', Array, Object(humhub\modules\missions\widgets\WallEntry)) #8 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(191): yii\base\View->render('entry', Array, Object(humhub\modules\missions\widgets\WallEntry)) #9 /home/ubuntu/humhub/protected/modules/missions/widgets/WallEntry.php(23): yii\base\Widget->render('entry', Array) #10 /home/ubuntu/humhub/protected/humhub/modules/content/widgets/WallEntry.php(109): humhub\modules\missions\widgets\WallEntry->run() #11 /home/ubuntu/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(124): humhub\modules\content\widgets\WallEntry->renderWallEntry() #12 /home/ubuntu/humhub/protected/modules/missions/components/actions/FixedStream.php(261): humhub\modules\content\components\ContentActiveRecord->getWallOut() #13 [internal function]: humhub\modules\missions\components\actions\FixedStream->run() #14 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array) #15 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array) #16 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('stream', Array) #17 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('missions/dashbo...', Array) #18 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #19 /home/ubuntu/humhub/index.php(25): yii\base\Application->run() #20 {main}
INFO  Tue, 07 Feb 2017 09:20:51 -0500  application
$_GET = [ 'r' => 'directory/directory/spaces' ] $_SERVER = [ 'HTTP_HOST' => 'literacy.evokenet.org' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' 'HTTP_REFERER' => 'http://literacy.evokenet.org/index.php?r=directory%2Fdirectory%2Fgroups' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,es;q=0.6' 'HTTP_COOKIE' => 'fs_uid=www.fullstory.com`21CH0`5649391675244544:5652720409116672; _csrf=0f6daa3ff6243b133d9939aba15720f57973e8e33f0278934f29cd7f02022b66a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22EO554q_v-Re94hQz6lKuQnDg2zsOHp9n%22%3B%7D; pm_space-members-panel=expanded; pm_user-spaces-panel=expanded; pm_groups-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_user-tags-panel=expanded; language=9af3597d700b1e74cb505508460e6f1f74ffdf917785b0817ba7ed34f85c4562a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; _gat=1; PHPSESSID=oif2pjaib1bfgl2g83obcfkp77; _ga=GA1.2.1211353109.1477168503; _identity=d6d341b77f54e53022cf4f94e2edfecb937cb2fca6757a886585d737cd6bc1cba%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A52%3A%22%5B241%2C%22d341a0cd-fa88-44d8-8653-d88369c26789%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at literacy.evokenet.org Port 80</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)' 'SERVER_NAME' => 'literacy.evokenet.org' 'SERVER_ADDR' => '172.31.32.11' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '97.88.214.229' 'DOCUMENT_ROOT' => '/var/www/html/humhub' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/html/humhub' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/var/www/html/humhub/index.php' 'REMOTE_PORT' => '55675' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=directory%2Fdirectory%2Fspaces' 'REQUEST_URI' => '/index.php?r=directory%2Fdirectory%2Fspaces' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1486477251.289 'REQUEST_TIME' => 1486477251 ]
ERROR  Tue, 07 Feb 2017 09:20:51 -0500  application
Could not load search result humhub\modules\space\models\Space - 65
INFO  Tue, 07 Feb 2017 09:20:47 -0500  application
$_GET = [ 'r' => 'missions/space/stream' 1 => '/missions/space/stream' 'limit' => '4' 'filters' => '' 'sort' => 'c' 'from' => '' 'mode' => 'normal' 'sguid' => '9e900336-d72a-4f14-ba0b-58e224df8bdd' ] $_SERVER = [ 'HTTP_HOST' => 'literacy.evokenet.org' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_ACCEPT' => 'application/json, text/javascript, */*; q=0.01' 'HTTP_X_CSRF_TOKEN' => 'TFZlN0Z0QXAJGVACcgUeBmEEAA5yHBAKejouQhcaBRd.LBZ4DgR4Hg==' 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' 'HTTP_REFERER' => 'http://literacy.evokenet.org/index.php?r=space%2Fspace&sguid=9e900336-d72a-4f14-ba0b-58e224df8bdd' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,es;q=0.6' 'HTTP_COOKIE' => 'fs_uid=www.fullstory.com`21CH0`5649391675244544:5652720409116672; _csrf=0f6daa3ff6243b133d9939aba15720f57973e8e33f0278934f29cd7f02022b66a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22EO554q_v-Re94hQz6lKuQnDg2zsOHp9n%22%3B%7D; pm_space-members-panel=expanded; pm_user-spaces-panel=expanded; pm_groups-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_user-tags-panel=expanded; language=9af3597d700b1e74cb505508460e6f1f74ffdf917785b0817ba7ed34f85c4562a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; _gat=1; PHPSESSID=oif2pjaib1bfgl2g83obcfkp77; _ga=GA1.2.1211353109.1477168503; _identity=d6d341b77f54e53022cf4f94e2edfecb937cb2fca6757a886585d737cd6bc1cba%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A52%3A%22%5B241%2C%22d341a0cd-fa88-44d8-8653-d88369c26789%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at literacy.evokenet.org Port 80</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)' 'SERVER_NAME' => 'literacy.evokenet.org' 'SERVER_ADDR' => '172.31.32.11' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '97.88.214.229' 'DOCUMENT_ROOT' => '/var/www/html/humhub' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/html/humhub' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/var/www/html/humhub/index.php' 'REMOTE_PORT' => '55676' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=missions%2Fspace%2Fstream&1=%2Fmissions%2Fspace%2Fstream&limit=4&filters=&sort=c&from=&mode=normal&sguid=9e900336-d72a-4f14-ba0b-58e224df8bdd' 'REQUEST_URI' => '/index.php?r=missions%2Fspace%2Fstream&1=%2Fmissions%2Fspace%2Fstream&limit=4&filters=&sort=c&from=&mode=normal&sguid=9e900336-d72a-4f14-ba0b-58e224df8bdd' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1486477247.933 'REQUEST_TIME' => 1486477247 ]
ERROR  Tue, 07 Feb 2017 09:20:48 -0500  yii\base\ErrorException:8
exception 'yii\base\ErrorException' with message 'Undefined offset: 0' in /home/ubuntu/humhub/protected/modules/missions/widgets/views/mentor_review.php:38 Stack trace: #0 /home/ubuntu/humhub/protected/modules/missions/widgets/views/mentor_review.php(38): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/home/ubuntu/hu...', 38, Array) #1 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(325): require('/home/ubuntu/hu...') #2 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/ubuntu/hu...', Array) #3 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/ubuntu/hu...', Array, NULL) #4 /home/ubuntu/humhub/protected/modules/missions/widgets/views/entry.php(142): yii\base\View->render('mentor_review', Array) #5 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(325): require('/home/ubuntu/hu...') #6 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/home/ubuntu/hu...', Array) #7 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/home/ubuntu/hu...', Array, Object(humhub\modules\missions\widgets\WallEntry)) #8 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(191): yii\base\View->render('entry', Array, Object(humhub\modules\missions\widgets\WallEntry)) #9 /home/ubuntu/humhub/protected/modules/missions/widgets/WallEntry.php(23): yii\base\Widget->render('entry', Array) #10 /home/ubuntu/humhub/protected/humhub/modules/content/widgets/WallEntry.php(109): humhub\modules\missions\widgets\WallEntry->run() #11 /home/ubuntu/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(124): humhub\modules\content\widgets\WallEntry->renderWallEntry() #12 /home/ubuntu/humhub/protected/modules/missions/components/actions/FixedStream.php(261): humhub\modules\content\components\ContentActiveRecord->getWallOut() #13 [internal function]: humhub\modules\missions\components\actions\FixedStream->run() #14 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array) #15 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams(Array) #16 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('stream', Array) #17 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('missions/space/...', Array) #18 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #19 /home/ubuntu/humhub/index.php(25): yii\base\Application->run() #20 {main}
INFO  Tue, 07 Feb 2017 09:20:44 -0500  application
$_GET = [ 'r' => 'directory/directory/spaces' ] $_SERVER = [ 'HTTP_HOST' => 'literacy.evokenet.org' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' 'HTTP_REFERER' => 'http://literacy.evokenet.org/index.php?r=directory%2Fdirectory%2Fgroups' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,es;q=0.6' 'HTTP_COOKIE' => 'fs_uid=www.fullstory.com`21CH0`5649391675244544:5652720409116672; _csrf=0f6daa3ff6243b133d9939aba15720f57973e8e33f0278934f29cd7f02022b66a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22EO554q_v-Re94hQz6lKuQnDg2zsOHp9n%22%3B%7D; pm_space-members-panel=expanded; pm_user-spaces-panel=expanded; pm_groups-statistics-panel=expanded; pm_new-spaces-panel=expanded; pm_new-people-panel=expanded; pm_user-statistics-panel=expanded; pm_user-tags-panel=expanded; language=9af3597d700b1e74cb505508460e6f1f74ffdf917785b0817ba7ed34f85c4562a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22en%22%3B%7D; _gat=1; PHPSESSID=oif2pjaib1bfgl2g83obcfkp77; _ga=GA1.2.1211353109.1477168503; _identity=d6d341b77f54e53022cf4f94e2edfecb937cb2fca6757a886585d737cd6bc1cba%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A52%3A%22%5B241%2C%22d341a0cd-fa88-44d8-8653-d88369c26789%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at literacy.evokenet.org Port 80</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)' 'SERVER_NAME' => 'literacy.evokenet.org' 'SERVER_ADDR' => '172.31.32.11' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '97.88.214.229' 'DOCUMENT_ROOT' => '/var/www/html/humhub' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/html/humhub' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/var/www/html/humhub/index.php' 'REMOTE_PORT' => '55674' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=directory%2Fdirectory%2Fspaces' 'REQUEST_URI' => '/index.php?r=directory%2Fdirectory%2Fspaces' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1486477244.454 'REQUEST_TIME' => 1486477244 ]
ERROR  Tue, 07 Feb 2017 09:20:44 -0500  application
Could not load search result humhub\modules\space\models\Space - 65

**Comment by Guihrmsfo** [comment]
The line that caused the exception:
$primaryPowerTitle = $activity->getPrimaryPowers()[0]->getPower()->title;
@JayantGandhi This is database related, can you take a look?

**Comment by nathanverrill** [comment]
So either 1) this occurs when I follow a team that has already submitted an evidence; or 2) because of the aforementioned power exception. 

I was able to create new accounts and follow a team before they submitted evidence, and then had the team submit evidence, and it worked A-OK.

**Comment by Guihrmsfo** [comment]
What's the status for this issue?

**Comment by nathanverrill** [comment]
If it's literacy related don't worry about it. We can come back to it later. Closing. Thanks for asking!
