### ISSUE TITLE
Edit Review doesn't work (mobile & web)

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#453]
Go to user profile
Click a link to one of the evidences reviewed
Click edit the first time, which opens the review panel
Click edit again in the little review box - button doesn't respond

<img width="352" alt="edit-no-worky" src="https://cloud.githubusercontent.com/assets/273429/22889274/22b41ba6-f1ce-11e6-87a6-9e34d64e1f7c.png">
<img width="775" alt="edit-on-web-doesnt-respond" src="https://cloud.githubusercontent.com/assets/273429/22889275/24e582d4-f1ce-11e6-8505-09483fe15d06.png">

**Comment by Guihrmsfo** [comment]
It's an old requirement that agents shouldn' be able to edit their reviews. Then the error is showing the edit button, not its malfunctioning. Should I implement an edit view for agents?
@JayantGandhi @nathanverrill

**Comment by nathanverrill** [comment]
Personally I think it would be good if players can edit their reviews because if we identify someone who is spamming, we can correct them, and then they can revise what they did previously, since our educational objective is to have good peer reviews. @JayantGandhi what are your thoughts?

**Comment by nathanverrill** [comment]
Meeting Conclusion: do not have the ability for users to edit their reviews.

**Comment by Guihrmsfo** [comment]
Obsolete because of #570
