### ISSUE TITLE
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "alliances/config"

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#468]
logged after viewing home as an admin

exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "alliances/config".' in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Module.php:460 Stack trace: #0 /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('alliances/confi...', Array) #1 /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #2 /srv/www/dev.humhub.m00.com.br/index.php(25): yii\base\Application->run() #3 {main} Next exception 'yii\web\NotFoundHttpException' with message 'Page not found.' in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/web/Application.php:96 Stack trace: #0 /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #1 /srv/www/dev.humhub.m00.com.br/index.php(25): yii\base\Application->run() #2 {main}

**Comment by JayantGandhi** [comment]
@nathanverrill I can't replicate this and there are no logs in the error log on admin

**Comment by nathanverrill** [comment]
@JayantGandhi it's resolved now - so something was pushed (?) that addressed it. Once I confirmed it was addressed then I flushed the log so I can lookout for more.

**Comment by JayantGandhi** [comment]
Ah ok, it was probably related to the other alliance bug then.
