### ISSUE TITLE
Error After Survey Results

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#47]
I filled out the agent type survey.
I left a field blank, got an error message, then corrected it.
I received the following error

PHP Fatal Error – yii\base\ErrorException

Call to a member function getPower() on a non-object
1. in /srv/www/dev.humhub.m00.com.br/protected/modules/matching_questions/views/matching-questions/matching-results.php at line 54
45464748495051525354555657585960616263                
                <div class="panel-heading sub-heading">
                  <?php echo Yii::t('MatchingModule.base', 'Your') ?>
                  <?= isset($quality_1->qualityTranslations[0]) ? $quality_1->qualityTranslations[0]->name : $quality_1->name ?>
                  <?php echo Yii::t('MatchingModule.base', 'Powers:') ?>
                </div>
                <div class="panel-body">
                  <div class="relevant-powers">
                    <?php foreach($relevant_powers as $user_power): ?>
                        <?php $power = $user_power->getPower(); ?>
                        <div class="relevant-power col-xs-6">
                          <div class="power-image" style="background-image:url('<?php echo $power->image; ?>')">
                          </div>
                          <div class="power-name">
                            <?php echo $power->title ?>
                          </div>
                          <div class="power-points-container">
                            <div class="power-points">
                              <?php echo $user_power->value ?> <?php echo Yii::t('MatchingModule.base', 'points') ?>
2. yii\base\ErrorHandler::handleFatalError()
$_GET = [
    'r' => 'matching_questions/matching-questions/matching',
];

$_POST = [
    '_csrf' => 'TXBTcHJwaE0uGCc/GgQPNQA9MSkRNCUvKRoSHyU2BgwhXREBIgI/Jg==',
    'matching_answer_13_matching_question_4' => '1',
    'matching_answer_14_matching_question_4' => '2',
    'matching_answer_15_matching_question_4' => '3',
    'matching_answer_16_matching_question_4' => '4',
    'matching_answer_17_matching_question_5' => '4',
    'matching_answer_18_matching_question_5' => '3',
    'matching_answer_19_matching_question_5' => '2',
    'matching_answer_20_matching_question_5' => '1',
    'matching_question_6' => '1',
    'matching_question_7' => '3',
    'matching_question_8' => '5',
    'matching_question_9' => '7',
    'matching_question_10' => '9',
    'matching_question_11' => '11',
];

$_COOKIE = [
    'PHPSESSID' => '6288vfu7shn5ljfpuu9r5378r7',
    '_csrf' => 'eb9e5148001cc750210508e63856a9de4f30be60c949a1a032d995ca0243b0c7a:2:{i:0;s:5:"_csrf";i:1;s:32:"chtOhtgxMMbYcDMbdjAoWFnAl-BqPrWk";}',
    'language' => '0f5dc5ff9d90b454f1f6efe09cb9011d1e1e04254e5e60c5c66138cf640adfe5a:2:{i:0;s:8:"language";i:1;s:2:"en";}',
    'pm_space-members-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'token' => 't.9AwZIlvPdD3hsU0VsUHQ',
];

$_SESSION = [
    '__flash' => [
        'popup2' => -1,
    ],
    '__returnUrl' => '/',
    '__id' => 84,
    'popup2' => [
        'title' => 'Congratulations!',
        'message' => ' You have earned the Empathetic Activist super power!!',
    ],
];

**Comment by nathanverrill** [comment]
Is test_user_evocoin

84  test_user_evocoin   nathanverrill+yankee@gmail.com  Test User   Evocoin No  never

**Comment by nathanverrill** [comment]
It had the same problem when I didn't receive an error on the form.

I hit back and got the dashboard without error.

**Comment by Guihrmsfo** [comment]
Fixed.
