### ISSUE TITLE
Error on Home After Survey Results Failure

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#48]
After I completed survey results and got error, I tried to restart on the home page to create a new user and I received the following error.

Integrity constraint violation – yii\db\IntegrityException

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '84-breakingnews-seen' for key 'idx_user_setting'
The SQL being executed was: INSERT INTO `user_setting` (`user_id`, `module_id`, `name`, `value`) VALUES (84, 'breakingnews', 'seen', '1')
Error Info: Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry '84-breakingnews-seen' for key 'idx_user_setting'
)
↵
Caused by: PDOException
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '84-breakingnews-seen' for key 'idx_user_setting'

in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/db/Command.php at line 784
1. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/db/Schema.php at line 628
619620621622623624625626627628629630631632633634635636637 
        $exceptionClass = '\yii\db\Exception';
        foreach ($this->exceptionMap as $error => $class) {
            if (strpos($e->getMessage(), $error) !== false) {
                $exceptionClass = $class;
            }
        }
        $message = $e->getMessage()  . "\nThe SQL being executed was: $rawSql";
        $errorInfo = $e instanceof \PDOException ? $e->errorInfo : null;
        return new $exceptionClass($message, $errorInfo, (int) $e->getCode(), $e);
    }

```
/**
 * Returns a value indicating whether a SQL statement is for read purpose.
 * @param string $sql the SQL statement
 * @return boolean whether a SQL statement is for read purpose.
 */
public function isReadQuery($sql)
{
```
1. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/db/Command.php at line 794 – yii\db\Schema::convertException(PDOException, 'INSERT INTO `user_setting` (`use...')
2. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/db/Schema.php at line 448 – yii\db\Command::execute()
3. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/db/ActiveRecord.php at line 457 – yii\db\Schema::insert('user_setting', ['user_id' => 84, 'module_id' => 'breakingnews', 'name' => 'seen', 'value' => '1'])
4. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/db/ActiveRecord.php at line 427 – yii\db\ActiveRecord::insertInternal(null)
5. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 593 – yii\db\ActiveRecord::insert(true, null)
6. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/user/models/Setting.php at line 117 – yii\db\BaseActiveRecord::save()
   111112113114115116117118119120121122123        if ($value == "") { {
               if (!$record->isNewRecord) {
                   $record->delete();
               }
           }
       } else {
           $record->save();
       }
   }
   
   /**
   - Returns an User Setting
     *
7. in /srv/www/dev.humhub.m00.com.br/protected/modules/breakingnews/Module.php at line 24 – humhub\modules\user\models\Setting::Set(84, 'seen', true, 'breakingnews')
   18192021222324252627282930    {
       if (Yii::$app->user->isGuest) {
           return;
       }
   
   ```
   if (Setting::Get('active', 'breakingnews') && \humhub\modules\user\models\Setting::Get(Yii::$app->user->id, 'seen', 'breakingnews') != 1) {
       \humhub\modules\user\models\Setting::Set(Yii::$app->user->id, 'seen', true, 'breakingnews');
       $event->sender->addWidget(widgets\BreakingNewsWidget::className(), array(), array('sortOrder' => 1));
   }
   ```
   
   }
   
   public function getConfigUrl()
   {
8. humhub\modules\breakingnews\Module::onDashboardSidebarInit(yii\base\Event)
9. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Event.php at line 205 – call_user_func(['humhub\modules\breakingnews\Modu...', 'onDashboardSidebarInit'], yii\base\Event)
10. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Component.php at line 549 – yii\base\Event::trigger(humhub\modules\dashboard\widgets\Sidebar, 'init', null)
11. in /srv/www/dev.humhub.m00.com.br/protected/humhub/widgets/BaseStack.php at line 73 – yii\base\Component::trigger('init')
    67686970717273747576777879 
    /**
    - Initializes the sidebar widget.
      */
      public function init()
      {
      $this->trigger(self::EVENT_INIT);
      return parent::init();
      }
    
    /**
    - Runs the Navigation
      */
12. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Object.php at line 107 – humhub\widgets\BaseStack::init()
13. yii\base\Object::__construct(['widgets' => [['humhub\modules\activity\widgets...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]]])
14. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/di/Container.php at line 374 – ReflectionClass::newInstanceArgs([['widgets' => [['humhub\modules\activity\widgets...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]]]])
15. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/di/Container.php at line 153 – yii\di\Container::build('humhub\modules\dashboard\widgets...', [], ['widgets' => [['humhub\modules\activity\widgets...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]]])
16. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/BaseYii.php at line 344 – yii\di\Container::get('humhub\modules\dashboard\widgets...', [], ['widgets' => [['humhub\modules\activity\widgets...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]]])
17. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Widget.php at line 97 – yii\BaseYii::createObject(['widgets' => [['humhub\modules\activity\widgets...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]], 'class' => 'humhub\modules\dashboard\widgets...'])
18. in /srv/www/dev.humhub.m00.com.br/themes/Evoke/views/dashboard/dashboard/index.php at line 37 – yii\base\Widget::widget(['widgets' => [['humhub\modules\activity\widgets...', ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]]])
    3132333435363738394041            ?>
        </div>
        <div class="col-md-4 layout-sidebar-container">
            <?php
            echo \humhub\modules\dashboard\widgets\Sidebar::widget(['widgets' => [
                    [\humhub\modules\activity\widgets\Stream::className(), ['streamAction' => '/dashboard/dashboard/stream'], ['sortOrder' => 150]]
            ]]);
            ?>
        </div>
    </div>
    </div>
19. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/srv/www/dev.humhub.m00.com.br/t...')
20. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/srv/www/dev.humhub.m00.com.br/t...', ['showProfilePostForm' => '1'])
21. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/srv/www/dev.humhub.m00.com.br/p...', ['showProfilePostForm' => '1'], humhub\modules\dashboard\controllers\DashboardController)
22. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Controller.php at line 377 – yii\base\View::render('index', ['showProfilePostForm' => '1'], humhub\modules\dashboard\controllers\DashboardController)
23. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/dashboard/controllers/DashboardController.php at line 53 – yii\base\Controller::render('index', ['showProfilePostForm' => '1'])
    47484950515253545556575859     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->render('index_guest', array());
        } else {
            return $this->render('index', array('showProfilePostForm' => Setting::Get('showProfilePostForm', 'dashboard')));
        }
    }
    
    /*
    - Update user settings for hiding share panel on dashboard
      */
24. humhub\modules\dashboard\controllers\DashboardController::actionIndex()
25. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\dashboard\controllers\DashboardController, 'actionIndex'], [])
26. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams([])
27. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('', [])
28. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('', [])
29. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
30. in /srv/www/dev.humhub.m00.com.br/index.php at line 25 – yii\base\Application::run()
    19202122232425    require(**DIR** . '/protected/humhub/config/web.php'),
    (is_readable(**DIR** . '/protected/config/dynamic.php')) ? require(**DIR** . '/protected/config/dynamic.php') : [],
    require(**DIR** . '/protected/config/common.php'),
    require(**DIR** . '/protected/config/web.php')
    );

(new humhub\components\Application($config))->run();
 $_COOKIE = [
    'PHPSESSID' => '6288vfu7shn5ljfpuu9r5378r7',
    '_csrf' => 'eb9e5148001cc750210508e63856a9de4f30be60c949a1a032d995ca0243b0c7a:2:{i:0;s:5:"_csrf";i:1;s:32:"chtOhtgxMMbYcDMbdjAoWFnAl-BqPrWk";}',
    'language' => '0f5dc5ff9d90b454f1f6efe09cb9011d1e1e04254e5e60c5c66138cf640adfe5a:2:{i:0;s:8:"language";i:1;s:2:"en";}',
    'pm_space-members-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'token' => 't.9AwZIlvPdD3hsU0VsUHQ',
];

$_SESSION = [
    '__flash' => [
        'popup2' => -1,
    ],
    '__returnUrl' => '/',
    '__id' => 84,
    'popup2' => [
        'title' => 'Congratulations!',
        'message' => ' You have earned the Empathetic Activist super power!!',
    ],
];
Yii Framework
2016-07-24, 12:46:32

Apache
Yii Framework/2.0.7

**Comment by nathanverrill** [comment]
Is test_user_evocoin

84  test_user_evocoin   nathanverrill+yankee@gmail.com  Test User   Evocoin No  never

**Comment by JayantGandhi** [comment]
looks like this is caused by the 'breaking news' module I added to see if we could use it for announcements.... I'll uninstall it now

**Comment by JayantGandhi** [comment]
fixed
