### ISSUE TITLE
If 'Alliances' module is not enabled, Review Evidences page breaks

### ISSUE THREAD

**Issue by rjapur** [EvokeNet/humhub#480]
It happened on my local, so it's not so urgent, but it's good to keep an eye on it

![review](https://cloud.githubusercontent.com/assets/4522059/23078256/16353234-f52f-11e6-8e50-0846b430cba1.png)

**Comment by JayantGandhi** [comment]
There are a lot of bugs like this (it's not just alliances) because of how interconnected all the different modules have become....
