### ISSUE TITLE
Error when trying to save edited review

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#484]
I rated an evidence 2-star as a mentor and submitted - worked fine
I edited the rating, changed to a 3-star and submitted - received error box 4 times and then it said it was submitted

http://dev.humhub.m00.com.br/index.php?r=user%2Fprofile&uguid=c92c3adf-3c58-49d4-9bf7-f223aaff8159

haven't been able to recreate so something to keep an eye out for

**Comment by Guihrmsfo** [comment]
I can't replicate this either, so I'm closing it.
