### ISSUE TITLE
error when tagging evidence

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#513]
Logged in as Evoke Bot
http://soacha.evokenet.org/index.php?r=user%2Fprofile&uguid=a4d9a65a-cbfa-4a3d-b3e0-1d123e5dd4f7

Tagged an evidence successfully and then when the page reloaded I got the following error:

PHP Notice – yii\base\ErrorException

Trying to get property of non-object
1. in /home/ubuntu/humhub/protected/modules/missions/views/review/index.php at line 27
18192021222324252627282930313233343536$this->pageTitle = $title;
 
$firstPrimary = true;
$firstSecondary = true;
 
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h5 style="margin-top:10px"><?php echo $title; ?></h5>
        <input type="hidden" id="evidence_id" value="<?= $evidence->id ?>">
        <?php if(Yii::$app->user->getIdentity()->group->name != "Mentors"): ?>
        <span><?php echo Yii::t('MissionsModule.base', 'Help organize the Evoke Evidence database. Earn 1 Evocoin for every 5 Evidences you tag.'); ?></span>
        <?php endif; ?>
        <?php //if($activity): ?>
            <h6><?php //echo Yii::t('MissionsModule.base', '{first} of {total}', array('first' => ($evidence_count - $evidence_to_review_count + 1), 'total' => $evidence_count)); ?></h6>
        <?php //endif; ?>
    </div>
<?php if($activity): ?>
    <div class="panel-body">
2. in /home/ubuntu/humhub/protected/modules/missions/views/review/index.php at line 27 – yii\base\ErrorHandler::handleError(8, 'Trying to get property of non-ob...', '/home/ubuntu/humhub/protected/mo...', 27, ...)
21222324252627282930313233$firstSecondary = true;
 
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h5 style="margin-top:10px"><?php echo $title; ?></h5>
        <input type="hidden" id="evidence_id" value="<?= $evidence->id ?>">
        <?php if(Yii::$app->user->getIdentity()->group->name != "Mentors"): ?>
        <span><?php echo Yii::t('MissionsModule.base', 'Help organize the Evoke Evidence database. Earn 1 Evocoin for every 5 Evidences you tag.'); ?></span>
        <?php endif; ?>
        <?php //if($activity): ?>
            <h6><?php //echo Yii::t('MissionsModule.base', '{first} of {total}', array('first' => ($evidence_count - $evidence_to_review_count + 1), 'total' => $evidence_count)); ?></h6>
        <?php //endif; ?>
3. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/home/ubuntu/humhub/protected/mo...')
4. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/home/ubuntu/humhub/protected/mo...', ['contentContainer' => humhub\modules\space\models\Space, 'evidence' => null, 'files' => null, 'evidence_count' => '4', ...])
5. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/home/ubuntu/humhub/protected/mo...', ['contentContainer' => humhub\modules\space\models\Space, 'evidence' => null, 'files' => null, 'evidence_count' => '4', ...], humhub\modules\missions\controllers\ReviewController)
6. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 377 – yii\base\View::render('index', ['contentContainer' => humhub\modules\space\models\Space, 'evidence' => null, 'files' => null, 'evidence_count' => '4', ...], humhub\modules\missions\controllers\ReviewController)
7. in /home/ubuntu/humhub/protected/modules/missions/controllers/ReviewController.php at line 169 – yii\base\Controller::render('index', ['contentContainer' => humhub\modules\space\models\Space, 'evidence' => null, 'files' => null, 'evidence_count' => '4', ...])
163164165166167168169170171172173174175            'evidence_to_review_count' => $evidence_to_review_count, 
            'tags' => $tags, 
            'is_ally' => $is_ally,
            'tagged_evidences' => $tagged_evidences,
            'next_to_evocoin' => $next_to_evocoin,
            )
        );
    }
 
    public function actionShow($id)
    {
        $user = Yii::$app->user->getIdentity();
 
8. humhub\modules\missions\controllers\ReviewController::actionIndex()
9. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\missions\controllers\ReviewController, 'actionIndex'], [])
10. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'missions/review/index', 'sguid' => '319af0e0-1c3a-4737-848e-88119c1c...'])
11. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('index', ['r' => 'missions/review/index', 'sguid' => '319af0e0-1c3a-4737-848e-88119c1c...'])
12. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('missions/review/index', ['r' => 'missions/review/index', 'sguid' => '319af0e0-1c3a-4737-848e-88119c1c...'])
13. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
14. in /home/ubuntu/humhub/index.php at line 25 – yii\base\Application::run()
19202122232425    require(__DIR__ . '/protected/humhub/config/web.php'),
    (is_readable(__DIR__ . '/protected/config/dynamic.php')) ? require(__DIR__ . '/protected/config/dynamic.php') : [],
    require(__DIR__ . '/protected/config/common.php'),
    require(__DIR__ . '/protected/config/web.php')
);
 
(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'missions/review/index',
    'sguid' => '319af0e0-1c3a-4737-848e-88119c1c7d62',
];

$_COOKIE = [
    'fs_uid' => 'www.fullstory.com`21CH0`5649391675244544:5652720409116672',
    'mp_d2557637bad0bf1520733bad76dd4c3d_mixpanel' => '{"distinct_id": "15a3833381d4cf-0560ed4058f148-1d3e6850-fa000-15a3833381e22f","$initial_referrer": "$direct","$initial_referring_domain": "$direct"}',
    '_csrf' => 'fcef2dfe8f83a30cdc2b1f56928703d6a825c10a7546215236092445145b10bda:2:{i:0;s:5:"_csrf";i:1;s:32:"1B33UCXHnRE-eaqyPY3BNZ5eptxDmtTs";}',
    'pm_getting-started-panel' => 'expanded',
    'pm_share-panel' => 'expanded',
    'pm_space-members-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'pm_groups-statistics-panel' => 'expanded',
    'pm_user-tags-panel' => 'expanded',
    'language' => 'b1b090445127dc6719f35d4624ccf58bb738c65e1924736baa3113382e631e72a:2:{i:0;s:8:"language";i:1;s:2:"en";}',
    'PHPSESSID' => '690kmqa05hcgbae8pcbhet01a0',
    '_gat' => '1',
    '_ga' => 'GA1.2.1195058208.1486493813',
    'pnctest' => '1',
    '_identity' => '9a33092da93987896ff3ce50b1edb52a01e2b6090c955fbc8be14a55bad9f81aa:2:{i:0;s:9:"_identity";i:1;s:50:"[3,"3893520c-4dac-4448-a65d-402193721150",2592000]";}',
];

$_SESSION = [
    '__flash' => [
        'popup' => -1,
    ],
    '__returnUrl' => '/index.php',
    '__id' => 8,
    'popup' => [
        [
            'title' => '¡Felicitaciones!',
            'message' => 'Gracias por etiquetar esta evidencía',
            'image_url' => null,
            'type' => null,
            'random' => 318424751,
        ],
    ],
];
Yii Framework
2017-02-21, 19:12:37

Apache/2.4.7 (Ubuntu)
Yii Framework/2.0.7

**Comment by nathanverrill** [comment]
Got the error on this evidence when logged in as Evoke Bot Jr

http://soacha.evokenet.org/index.php?r=missions%2Freview%2Findex&sguid=319af0e0-1c3a-4737-848e-88119c1c7d62

**Comment by JayantGandhi** [comment]
fixed
