### ISSUE TITLE
Submit Review doesn't respond when comment box is left blank

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#52]
Go to review evidence, click yes, enter a value for the rating, and leave comment box blank. No response. Add comment and submit, and it submits as expected.

On a 4MB connection

**Comment by Guihrmsfo** [comment]
Nathan, can you try again?
I have tested four times (3 of them on review evidences and once at an evidence on user stream) and works fine. 
Maybe the button didn't work at the first time for some reason.

**Comment by nathanverrill** [comment]
Still an issue...

http://dev.humhub.m00.com.br/index.php?r=missions%2Freview%2Findex&sguid=2c82a825-69dc-498a-bbc5-d72dfd0fd7bd

username: DuBois

**Comment by JayantGandhi** [comment]
![image](https://cloud.githubusercontent.com/assets/4398613/17145342/c5abfb30-5327-11e6-87d9-7fb7209112f2.png)

**Comment by Guihrmsfo** [comment]
I believe that's an intermittent issue. 
@rjapur helped me identify that it doesn't only return a feedback, but the review is sent. 
Also, it doesn't depend on whether comment box is left blank or not. 
I'm trying to figure it out its cause.

**Comment by Guihrmsfo** [comment]
@JayantGandhi 
Sorry, just saw your reply, that's the ajax response, right?
I'll take a look at that error. Thank you!

**Comment by Guihrmsfo** [comment]
Fixed. I'll update the server soon.

**Comment by Guihrmsfo** [comment]
Updated.
