### ISSUE TITLE
activity stream gets cutoff / hard to read sometimes

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#521]
on base of operations
![image](https://cloud.githubusercontent.com/assets/273429/23264502/25d2e71e-f9a7-11e6-830f-8a71bab3e1cc.png)

![image](https://cloud.githubusercontent.com/assets/273429/23264514/31b87828-f9a7-11e6-8f92-00a8ef47e9a2.png)

**Comment by Guihrmsfo** [comment]
It seems fine to me now, is this still happening to you?
 @nathanverrill

**Comment by nathanverrill** [comment]
I think it depends on how long the notification text is. There are only short messages in there right now so it looks fine. This is minor, so I'll close it and we can return to it in the future.
