### ISSUE TITLE
disable or fix email "news"

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#524]
currently I receive an email at 11pm, and wonder if the students do as well.

![image](https://cloud.githubusercontent.com/assets/273429/23308428/bd0280b2-fa70-11e6-8c5d-5a280fdc8630.png)

Should make it look & work better or disable altogether so students don't have to update their preferences.

**Comment by JayantGandhi** [comment]
@nathanverrill this is an email from the dev server

**Comment by nathanverrill** [comment]
Roger that. So to confirm they won't be sent out on production, correct? Thanks in advance.

**Comment by JayantGandhi** [comment]
Shouldn't be, I just double checked my spam folder and don't see anything and the settings are set to "never" on production

**Comment by nathanverrill** [comment]
roger that
