### ISSUE TITLE
investigate token not found

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#525]
Last night there were no account creations, however there was token not found error. Want to know if this is a user who was unable to signup for some reason. Does their token timeout perhaps? The error is from an IP in Colombia.

INFO  Thu, 23 Feb 2017 23:13:29 -0500  application
$_GET = [ 'r' => 'user/auth/create-account' 'token' => '57b64de4095b32034701041' ] $_SERVER = [ 'HTTP_HOST' => 'soacha.evokenet.org' 'HTTP_CONNECTION' => 'keep-alive' 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1' 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch' 'HTTP_ACCEPT_LANGUAGE' => 'es-ES,es;q=0.8' 'HTTP_COOKIE' => 'language=2e2c7fa0242766f45a734a15a20a634d37b58d606f6f05f0aad08c2640adbbeea%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22language%22%3Bi%3A1%3Bs%3A2%3A%22es%22%3B%7D; fs_uid=www.fullstory.com`21CH0`5757715179634688:5757793965441024; _ga=GA1.2.1857284106.1473801677; _identity=f6d2a141eba562a8837c4ac68d1950385172680d7a669d6a8df03c131fc94720a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A51%3A%22%5B98%2C%220a30407c-5b52-4b6c-8cbd-cb67226fd83a%22%2C2592000%5D%22%3B%7D' 'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' 'SERVER_SIGNATURE' => '<address>Apache/2.4.7 (Ubuntu) Server at soacha.evokenet.org Port 80</address> ' 'SERVER_SOFTWARE' => 'Apache/2.4.7 (Ubuntu)' 'SERVER_NAME' => 'soacha.evokenet.org' 'SERVER_ADDR' => '172.31.18.75' 'SERVER_PORT' => '80' 'REMOTE_ADDR' => '186.154.38.221' 'DOCUMENT_ROOT' => '/var/www/html/humhub' 'REQUEST_SCHEME' => 'http' 'CONTEXT_PREFIX' => '' 'CONTEXT_DOCUMENT_ROOT' => '/var/www/html/humhub' 'SERVER_ADMIN' => 'webmaster@localhost' 'SCRIPT_FILENAME' => '/var/www/html/humhub/index.php' 'REMOTE_PORT' => '49519' 'GATEWAY_INTERFACE' => 'CGI/1.1' 'SERVER_PROTOCOL' => 'HTTP/1.1' 'REQUEST_METHOD' => 'GET' 'QUERY_STRING' => 'r=user%2Fauth%2Fcreate-account&token=57b64de4095b32034701041' 'REQUEST_URI' => '/index.php?r=user%2Fauth%2Fcreate-account&token=57b64de4095b32034701041' 'SCRIPT_NAME' => '/index.php' 'PHP_SELF' => '/index.php' 'REQUEST_TIME_FLOAT' => 1487909609.366 'REQUEST_TIME' => 1487909609 ]
ERROR  Thu, 23 Feb 2017 23:13:29 -0500  yii\web\HttpException:404
exception 'yii\web\HttpException' with message 'Token not found!' in /home/ubuntu/humhub/protected/humhub/modules/user/controllers/AuthController.php:181 Stack trace: #0 [internal function]: humhub\modules\user\controllers\AuthController->actionCreateAccount() #1 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array) #2 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array) #3 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('create-account', Array) #4 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('user/auth/creat...', Array) #5 /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(humhub\components\Request)) #6 /home/ubuntu/humhub/index.php(25): yii\base\Application->run() #7 {main}

**Comment by rjapur** [comment]
The token either was timeout or the person required sign up more than once and instead of accessing the latest email, it probably clicked on a previous one. @guihrmsfo are you aware of other cases this can happen?

**Comment by Guihrmsfo** [comment]
I'd say the person who caused this issue created his account already then tried to access the same URL for some reason.
