### ISSUE TITLE
After submitting evidence the trophy messages for powers were displayed twice - Curiosity, Gen Spirit, Curiosity Gen Spirit

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#531]
link associated with showing: borrador guardado! message in console

![image](https://cloud.githubusercontent.com/assets/273429/23322570/311624e8-faaa-11e6-9679-6451530c7184.png)

**Comment by nathanverrill** [comment]
In this scenario I had attached an image

**Comment by Guihrmsfo** [comment]
Is this still happening?
