### ISSUE TITLE
Power Names not displayed on success message

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#532]
Submit an evidence so you get the trophy message.
Power names are not included on the message.
This occurred in both English and Spanish on different sets of activities.

![image](https://cloud.githubusercontent.com/assets/273429/23322854/80576afc-faab-11e6-8abc-f0d869352e94.png)

**Comment by Guihrmsfo** [comment]
They are being displayed for me, can you confirm if the box isn't completely visible?
I want to make sure I'm trying to fix the correct error.

**Comment by nathanverrill** [comment]
They aren't displayed after saving draft and then submitting.

**Comment by nathanverrill** [comment]
...but they are if I don't save a draft first.

**Comment by nathanverrill** [comment]
This is fixed now. Closing.
