### ISSUE TITLE
after saving draft and then publishing, submit evidence form still displayed

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#551]
navigate to activity
enter evidence
save draft
publish
then submitted evidence is displayed with submit evidence form below

![image](https://cloud.githubusercontent.com/assets/273429/23672933/3d10ef70-0325-11e7-8433-b3507a4a2b0f.png)

**Comment by nathanverrill** [comment]
Also, award messages (powers earned) are not displayed

**Comment by Guihrmsfo** [comment]
Duplicated #530
