### ISSUE TITLE
when I submit an evidence I get two notifications that my power points have increased

### ISSUE THREAD

**Issue by JayantGandhi** [EvokeNet/humhub#57]
the alert shows twice
~~it also does not look like my powers were updated~~

**Comment by JayantGandhi** [comment]
also, only awards 1 point, should be 10, but this is an outstanding issue where all those point awards need to be 10x greater than they currently are

**Comment by Guihrmsfo** [comment]
I failed at replicating the error, does it keep happening?

**Comment by JayantGandhi** [comment]
No, fixed
