### ISSUE TITLE
After creating evokation deadline in the past, evokation portfolio/voting functionality does not appear

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#59]
I went into the admin and created an evokation deadline, start in the past, end in the future.

I was expecting the Evokation portfolio, create and voting functionality to be revealed, it was not.

Perhaps I'm missing something and this is not a bug?

**Comment by Guihrmsfo** [comment]
Did you enable evokations on 'Evoke Settings'?

**Comment by nathanverrill** [comment]
Awesome, that did the trick

Cheers

Nathan
