### ISSUE TITLE
site crash with database connection error

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#62]
@msoledade can you add some more detail and how you fixed it?

It occurred when we had multiple people in the mentor role on the site.

**Comment by nathanverrill** [comment]
They also were on the same team, reviewing evidence and clicking through the site. I also was clicking through the site as an admin, not reviewing, just seeing activity streams and the leaderboard.

**Comment by nathanverrill** [comment]
Will be checking with load test on production. Also need to simulate multiple simultaneous mentor reviews.

**Comment by nathanverrill** [comment]
Currently receiving the following error on production:

Database Exception – yii\db\Exception

SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)
↵
Caused by: PDOException

SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)

in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/Connection.php at line 600
1. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/Connection.php at line 547
538539540541542543544545546547548549550551552553554555556        $token = 'Opening DB connection: ' . $this->dsn;
        try {
            Yii::info($token, **METHOD**);
            Yii::beginProfile($token, **METHOD**);
            $this->pdo = $this->createPdoInstance();
            $this->initConnection();
            Yii::endProfile($token, **METHOD**);
        } catch (\PDOException $e) {
            Yii::endProfile($token, **METHOD**);
            throw new Exception($e->getMessage(), $e->errorInfo, (int) $e->getCode(), $e);
        }
    }

```
/**
 * Closes the currently active DB connection.
 * It does nothing if the connection is already closed.
 */
public function close()
{
```
1. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/Connection.php at line 858 – yii\db\Connection::open()
2. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/Connection.php at line 845 – yii\db\Connection::getMasterPdo()
3. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 219 – yii\db\Connection::getSlavePdo()
4. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 834 – yii\db\Command::prepare(true)
5. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/Command.php at line 362 – yii\db\Command::queryInternal('fetchAll', null)
6. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/Query.php at line 210 – yii\db\Command::queryAll()
7. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php at line 133 – yii\db\Query::all(null)
8. in /home/ubuntu/humhub/protected/humhub/models/ModuleEnabled.php at line 63 – yii\db\ActiveQuery::all()
   57585960616263646566676869 
   public static function getEnabledIds()
   {
       $enabledModules = Yii::$app->cache->get(self::CACHE_ID_ALL_IDS);
       if ($enabledModules === false) {
           $enabledModules = [];
           foreach (\humhub\models\ModuleEnabled::find()->all() as $em) {
               $enabledModules[] = $em->module_id;
           }
           Yii::$app->cache->set(self::CACHE_ID_ALL_IDS, $enabledModules);
       }
       return $enabledModules;
   }
9. in /home/ubuntu/humhub/protected/humhub/components/ModuleManager.php at line 71 – humhub\models\ModuleEnabled::getEnabledIds()
   65666768697071727374757677            return;
       }
   
   ```
   if (Yii::$app instanceof console\Application && !Yii::$app->isDatabaseInstalled()) {
       $this->enabledModules = [];
   } else {
       $this->enabledModules = \humhub\models\ModuleEnabled::getEnabledIds();
   }
   ```
   
   }
   
   /**
   - Registers a module to the manager
   - This is usally done by autostart.php in modules root folder.
10. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Object.php at line 107 – humhub\components\ModuleManager::init()
11. yii\base\Object::__construct([])
12. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/di/Container.php at line 368 – ReflectionClass::newInstanceArgs([[]])
13. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/di/Container.php at line 153 – yii\di\Container::build('\humhub\components\ModuleManager', [], [])
14. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/BaseYii.php at line 344 – yii\di\Container::get('\humhub\components\ModuleManager', [], [])
15. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php at line 133 – yii\BaseYii::createObject(['class' => '\humhub\components\ModuleManager'])
16. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/di/ServiceLocator.php at line 71 – yii\di\ServiceLocator::get('moduleManager')
17. in /home/ubuntu/humhub/protected/humhub/components/bootstrap/ModuleAutoLoader.php at line 52 – yii\di\ServiceLocator::__get('moduleManager')
    46474849505152535455            }
            if (!YII_DEBUG) {
                Yii::$app->cache->set(self::CACHE_ID, $modules);
            }
        }
    
    ```
    Yii::$app->moduleManager->registerBulk($modules);
    ```
    
    }

}
19. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 315 – humhub\components\bootstrap\ModuleAutoLoader::bootstrap(humhub\components\Application)
20. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/web/Application.php at line 63 – yii\base\Application::bootstrap()
21. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 267 – yii\web\Application::bootstrap()
22. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Object.php at line 107 – yii\base\Application::init()
23. in /home/ubuntu/humhub/protected/vendor/yiisoft/yii2/base/Application.php at line 206 – yii\base\Object::**construct(['name' => 'Evoke', 'version' => '1.0.0', 'bootstrap' => ['log', 'humhub\components\bootstrap\Modu...', 'humhub\components\bootstrap\Lang...'], 'language' => 'es', ...])
24. in /home/ubuntu/humhub/index.php at line 25 – yii\base\Application::__construct(['name' => 'Evoke', 'version' => '1.0.0', 'basePath' => '/home/ubuntu/humhub/protected/hu...', 'bootstrap' => ['log', 'humhub\components\bootstrap\Modu...', 'humhub\components\bootstrap\Lang...'], ...])
19202122232425    require(__DIR** . '/protected/humhub/config/web.php'),
    (is_readable(**DIR** . '/protected/config/dynamic.php')) ? require(**DIR** . '/protected/config/dynamic.php') : [],
    require(**DIR** . '/protected/config/common.php'),
    require(**DIR** . '/protected/config/web.php')
);

(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'space/space',
    'sguid' => '6efd65de-3fdf-4d5f-ab28-9e312aec8e24',
];

$_COOKIE = [
    '_csrf' => 'bac27e7aeae3a16b9cbae2173123f6c1dfc6f827c13739bbd8d890d2f6e409d4a:2:{i:0;s:5:"_csrf";i:1;s:32:"lfl602TsmYSnaguz8MigNYgASQnc3npU";}',
    'pm_getting-started-panel' => 'expanded',
    'pm_space-members-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'pm_profile-follower-panel' => 'expanded',
    'language' => '2e2c7fa0242766f45a734a15a20a634d37b58d606f6f05f0aad08c2640adbbeea:2:{i:0;s:8:"language";i:1;s:2:"es";}',
    'PHPSESSID' => 'c507cd2cpb1krjsj7et2ielgh3',
    '_ga' => 'GA1.2.1926725822.1471014321',
    '_identity' => '5e02b94f95d1800b82cd231f5f2405bed5c72f091b4788b0a0cd3adf2ff7333aa:2:{i:0;s:9:"_identity";i:1;s:51:"[23,"40f1ec75-9d6b-47ac-b453-6c1d04340aac",2592000]";}',
];
Yii Framework
2016-08-12, 11:52:36

Apache/2.4.7 (Ubuntu)
Yii Framework/2.0.7

**Comment by JayantGandhi** [comment]
This should be solved with the new setup
