### ISSUE TITLE
Mentor name not displayed with evidence review when viewing my own evidence

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#69]
I created three accounts:

eleanor, who authored an evidence
http://dev.humhub.m00.com.br/index.php?r=user%2Fprofile&uguid=8be3109d-d648-4f0d-a67e-f0ec56a24d6f

AUG 2 Team A Player 1, who submitted a review

Aug 2 Mentor, who submitted a review

When eleanor, the evidence author, viewed her reviews, both reviews were anonymous. The Mentor review should have showed the mentor name.

<img width="752" alt="show_mentor_name" src="https://cloud.githubusercontent.com/assets/273429/17346270/7a7779ac-58cf-11e6-8f44-da54534d5457.png">

When I viewed Eleanor's evidence as a mentor, I could see both review authors as expected.

**Comment by Guihrmsfo** [comment]
@nathanverrill 
Please, test it again.

**Comment by nathanverrill** [comment]
Perfect!
