### ISSUE TITLE
PHP error when trying to view members for base of operations

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#71]
With username Nathan Verrill went to base of operations, clicked the settings gear, and chose members. Received the following error:

PHP Notice – yii\base\ErrorException

Trying to get property of non-object
1. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/space/modules/manage/views/member/index.php at line 35
26272829303132333435363738394041424344                    'user.username',
                    'user.profile.firstname',
                    'user.profile.lastname',
                    [
                        'label' => Yii::t('SpaceModule.views_admin_members', 'Group'),
                        'class' => 'humhub\libs\DropDownGridColumn',
                        'attribute' => 'group_id',
                        'submitAttributes' => ['user_id'],
                        'readonly' => function ($data) use ($space) {
                    if ($space->isSpaceOwner($data->user->id)) {
                        return true;
                    }
                    return false;
                },
                        'filter' => $groups,
                        'dropDownOptions' => $groups,
                        'value' =>
                        function ($data) use (&$groups, $space) {
                    return $groups[$data->group_id];
2. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/space/modules/manage/views/member/index.php at line 35 – yii\base\ErrorHandler::handleError(8, 'Trying to get property of non-ob...', '/srv/www/dev.humhub.m00.com.br/p...', 35, ...)
29303132333435363738394041                    [
                        'label' => Yii::t('SpaceModule.views_admin_members', 'Group'),
                        'class' => 'humhub\libs\DropDownGridColumn',
                        'attribute' => 'group_id',
                        'submitAttributes' => ['user_id'],
                        'readonly' => function ($data) use ($space) {
                    if ($space->isSpaceOwner($data->user->id)) {
                        return true;
                    }
                    return false;
                },
                        'filter' => $groups,
                        'dropDownOptions' => $groups,
3. yii\base\View::{closure}(humhub\modules\space\models\Membership, ['space_id' => 1, 'user_id' => 63], 5, humhub\libs\DropDownGridColumn)
4. in /srv/www/dev.humhub.m00.com.br/protected/humhub/libs/DropDownGridColumn.php at line 100 – call_user_func(Closure, humhub\modules\space\models\Membership, ['space_id' => 1, 'user_id' => 63], 5, ...)
949596979899100101102103104105106        }

```
    $inputName = (is_array($model)) ? $this->attribute : Html::getInputName($model, $this->attribute);

    $readonly = $this->readonly;
    if (!is_bool($readonly)) {
        $readonly = call_user_func($this->readonly, $model, $key, $index, $this);
    }

    if ($readonly) {
        if (isset($options[$model[$this->attribute]])) {
            return $options[$model[$this->attribute]];
        }
```
1. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/grid/Column.php at line 108 – humhub\libs\DropDownGridColumn::renderDataCellContent(humhub\modules\space\models\Membership, ['space_id' => 1, 'user_id' => 63], 5)
2. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/grid/GridView.php at line 504 – yii\grid\Column::renderDataCell(humhub\modules\space\models\Membership, ['space_id' => 1, 'user_id' => 63], 5)
3. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/grid/GridView.php at line 473 – yii\grid\GridView::renderTableRow(humhub\modules\space\models\Membership, ['space_id' => 1, 'user_id' => 63], 5)
4. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/grid/GridView.php at line 344 – yii\grid\GridView::renderTableBody()
5. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/widgets/BaseListView.php at line 151 – yii\grid\GridView::renderItems()
6. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/grid/GridView.php at line 313 – yii\widgets\BaseListView::renderSection('{items}')
7. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/widgets/BaseListView.php at line 126 – yii\grid\GridView::renderSection('{items}')
8. yii\widgets\BaseListView::yii\widgets{closure}(['{items}'])
9. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/widgets/BaseListView.php at line 129 – preg_replace_callback('/{\w+}/', Closure, '{summary} {items} {pager}')
10. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/grid/GridView.php at line 288 – yii\widgets\BaseListView::run()
11. in /srv/www/dev.humhub.m00.com.br/protected/humhub/widgets/GridView.php at line 46 – yii\grid\GridView::run()
    40414243444546474849                $(".grid-view-loading").css("display", "block !important");
                $(".grid-view-loading").css("opacity", "1 !important");
        });';
    
    ```
    $this->getView()->registerJs($loaderJs);
    
    return parent::run();
    ```
    
    }

}
16. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Widget.php at line 98 – humhub\widgets\GridView::run()
17. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/space/modules/manage/views/member/index.php at line 78 – yii\base\Widget::widget(['dataProvider' => yii\data\ActiveDataProvider, 'filterModel' => humhub\modules\space\modules\manage\models\MembershipSearch, 'columns' => ['user.username', 'user.profile.firstname', 'user.profile.lastname', ['label' => 'Group', 'class' => 'humhub\libs\DropDownGridColumn', 'attribute' => 'group_id', 'submitAttributes' => ['user_id'], ...], ...]])
7273747576777879808182                                            'update' => function () {
                                        return;
                                    },
                                        ],
                                    ],
                                ],
                            ]);
                            ?>
        </div>
    </div>
</div>
18. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/srv/www/dev.humhub.m00.com.br/p...')
19. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/srv/www/dev.humhub.m00.com.br/p...', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\space\modules\manage\models\MembershipSearch, 'space' => humhub\modules\space\models\Space])
20. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/srv/www/dev.humhub.m00.com.br/p...', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\space\modules\manage\models\MembershipSearch, 'space' => humhub\modules\space\models\Space], humhub\modules\space\modules\manage\controllers\MemberController)
21. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Controller.php at line 377 – yii\base\View::render('index', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\space\modules\manage\models\MembershipSearch, 'space' => humhub\modules\space\models\Space], humhub\modules\space\modules\manage\controllers\MemberController)
22. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/space/modules/manage/controllers/MemberController.php at line 59 – yii\base\Controller::render('index', ['dataProvider' => yii\data\ActiveDataProvider, 'searchModel' => humhub\modules\space\modules\manage\models\MembershipSearch, 'space' => humhub\modules\space\models\Space])
53545556575859606162636465        }

```
    return $this->render('index', array(
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
                'space' => $space
    ));
}

/**
 * Members Administration Action
 */
public function actionPendingInvitations()
```
1. humhub\modules\space\modules\manage\controllers\MemberController::actionIndex()
2. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\space\modules\manage\controllers\MemberController, 'actionIndex'], [])
3. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'space/manage/member', 'sguid' => '2c343926-6781-4256-9a1b-10a9b29b...'])
4. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('', ['r' => 'space/manage/member', 'sguid' => '2c343926-6781-4256-9a1b-10a9b29b...'])
5. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('space/manage/member', ['r' => 'space/manage/member', 'sguid' => '2c343926-6781-4256-9a1b-10a9b29b...'])
6. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
7. in /srv/www/dev.humhub.m00.com.br/index.php at line 25 – yii\base\Application::run()
   19202122232425    require(**DIR** . '/protected/humhub/config/web.php'),
   (is_readable(**DIR** . '/protected/config/dynamic.php')) ? require(**DIR** . '/protected/config/dynamic.php') : [],
   require(**DIR** . '/protected/config/common.php'),
   require(**DIR** . '/protected/config/web.php')
   );

(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'space/manage/member',
    'sguid' => '2c343926-6781-4256-9a1b-10a9b29b7b51',
];

$_COOKIE = [
    '_csrf' => '300058683ebf01dd80e043f4e918e6734aa73c15714aa5a39475a6a3da7681e1a:2:{i:0;s:5:"_csrf";i:1;s:32:"GRNojp_o59wcW3OzVwnhz08fZxMgfPiN";}',
    'pm_space-members-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'pm_profile-follower-panel' => 'expanded',
    'pm_profile-following-panel' => 'expanded',
    'pm_groups-statistics-panel' => 'expanded',
    'pm_new-spaces-panel' => 'expanded',
    'language' => '0f5dc5ff9d90b454f1f6efe09cb9011d1e1e04254e5e60c5c66138cf640adfe5a:2:{i:0;s:8:"language";i:1;s:2:"en";}',
    'PHPSESSID' => '7lmnncmmj226ibtoephqgvhun7',
    '_identity' => '276de92d0ab515b0398955cd432b6c9ede0ac43f15ecccb46fb05ce1e56cf4e0a:2:{i:0;s:9:"_identity";i:1;s:51:"[60,"2a049146-73d4-463e-9ac9-444b413c7bab",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/index.php',
    '__captcha/user/auth/captcha' => 'uywobu',
    '__captcha/user/auth/captchacount' => 2,
    '__id' => 60,
];
Yii Framework
2016-08-02, 19:35:51

Apache
Yii Framework/2.0.7

**Comment by nathanverrill** [comment]
User Name 
Nathan Verrill

Password
Soacha

**Comment by Guihrmsfo** [comment]
Nonexistent user in space. It may be a remaining error from last database cleaning.
Fixed.
