### ISSUE TITLE
Mentor reviews not counted as 2x

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#77]
Player AUG 2 Team A Captain submitted evidence for M2A1
Received +5 Curiosity as expected for submitting the evidence.

Eleanor, a player, reviewed evidence. Submitter received +5 curiosity.

Aug 2 Mentor submitted a review, and the submitter received +5 curiosity, instead of +10.

**Comment by JayantGandhi** [comment]
#80
