### ISSUE TITLE
Sign up after email invite not in Spanish

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#79]
Site is set to Spanish by default

Invite is sent by Alchemy user; Alchemy's language preference is set to Spanish when sending the email

User receives email in Spanish

User navigates to the site to sign up.

Sign up form is in English.

---

I tried it after clearing cookies and still had the same problem.

I was able to get it to display the sign up form in Spanish by going to the home page first, and choosing Spanish from the language drop down by sign up.

**Comment by nathanverrill** [comment]
If this is a tough, time-consuming bug, we might consider having the form always be in Spanish, and then we can work on fixing the English after... :)

**Comment by nathanverrill** [comment]
I can make it work properly if I'm logged into evoke already, log out, and then go to the link in the same browser. It's when I go to a different browser with no cookies that I have a problem.

**Comment by rjapur** [comment]
getting in touch with lucas to see how to solve this

**Comment by nathanverrill** [comment]
Is there a way for us to do this in the "not right way" in the meantime, defaulting to Spanish, then making it right later? This is a critical fix that should be addressed as quickly as possible. The form doesn't have to be displayed in English. 

The other option is that we show both languages in labels, like this: {spanish label} / {english label}

Anyway, has to be addressed as soon as possible... Thank you!

**Comment by nathanverrill** [comment]
@rjapur what are your thoughts on this question?

**Comment by nathanverrill** [comment]
This is only when an invitation to a space is sent.
Closing as we'll change the onboarding flow and send users to the standard home page and signup flow.
