### ISSUE TITLE
Division by zero error on Review Evidence

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#81]
Occurs with admins and regular users and on spaces. 

PHP Warning – yii\base\ErrorException

Division by zero
1. in /srv/www/dev.humhub.m00.com.br/protected/modules/stats/widgets/views/customSpaceHeader.php at line 223
214215216217218219220221222223224225226227228229230231232                        </div>

```
                    <div class="pull-left entry">
                        <span class="count"><?php echo $done.'/'.$total; ?></span><br>
                        <span
                            class="title"><?php echo Yii::t('StatsModule.widgets_views_spaceHeader', 'Activities Completed'); ?></span>
                    </div>

                    <!-- <div class="pull-left entry" style = "margin-top:10px"> -->
                        <!--<span class="count"><?php echo floor(($done/$total)*100).'%'; ?></span><br>
                        <span
                            class="title"><?php echo Yii::t('StatsModule.widgets_views_spaceHeader', 'Evokation Progress'); ?></span>-->
                        <!-- <div class="progress" style = "width:150px">
                            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <?= floor(($done/$total)*100) ?>%;">
                                <span class="sr-only"></span>
                            </div>
                        </div> -->
                    <!-- </div> -->
```
1. in /srv/www/dev.humhub.m00.com.br/protected/modules/stats/widgets/views/customSpaceHeader.php at line 223 – yii\base\ErrorHandler::handleError(2, 'Division by zero', '/srv/www/dev.humhub.m00.com.br/p...', 223, ...)
   217218219220221222223224225226227228229                            <span class="count"><?php echo $done.'/'.$total; ?></span><br>
                           <span
                               class="title"><?php echo Yii::t('StatsModule.widgets_views_spaceHeader', 'Activities Completed'); ?></span>
                       </div>
   
   ```
                   <!-- <div class="pull-left entry" style = "margin-top:10px"> -->
                       <!--<span class="count"><?php echo floor(($done/$total)*100).'%'; ?></span><br>
                       <span
                           class="title"><?php echo Yii::t('StatsModule.widgets_views_spaceHeader', 'Evokation Progress'); ?></span>-->
                       <!-- <div class="progress" style = "width:150px">
                           <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <?= floor(($done/$total)*100) ?>%;">
                               <span class="sr-only"></span>
                           </div>
   ```
2. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/srv/www/dev.humhub.m00.com.br/p...')
3. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/srv/www/dev.humhub.m00.com.br/p...', ['mission' => [app\modules\missions\models\Missions, app\modules\missions\models\Missions], 'total' => '0', 'done' => '0', 'evidencesTotal' => '0', ...])
4. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/srv/www/dev.humhub.m00.com.br/p...', ['mission' => [app\modules\missions\models\Missions, app\modules\missions\models\Missions], 'total' => '0', 'done' => '0', 'evidencesTotal' => '0', ...], humhub\modules\stats\widgets\CustomSpaceHeader)
5. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Widget.php at line 191 – yii\base\View::render('customSpaceHeader', ['mission' => [app\modules\missions\models\Missions, app\modules\missions\models\Missions], 'total' => '0', 'done' => '0', 'evidencesTotal' => '0', ...], humhub\modules\stats\widgets\CustomSpaceHeader)
6. in /srv/www/dev.humhub.m00.com.br/protected/modules/stats/widgets/CustomSpaceHeader.php at line 52 – yii\base\Widget::render('customSpaceHeader', ['mission' => [app\modules\missions\models\Missions, app\modules\missions\models\Missions], 'total' => '0', 'done' => '0', 'evidencesTotal' => '0', ...])
   464748495051525354555657                    'mission' => $missions,
                   'total' => $total,
                   'done' => $done,
                   'evidencesTotal' => $evidencesTotal,
                   'space' => $this->space,
                   'postCount' => $postCount
       ));
   }

}

?>
8. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Widget.php at line 98 – humhub\modules\stats\widgets\CustomSpaceHeader::run()
9. in /srv/www/dev.humhub.m00.com.br/themes/Evoke/views/space/space/_layout.php at line 7 – yii\base\Widget::widget(['space' => humhub\modules\space\models\Space])
12345678910111213<?php
$space = $this->context->contentContainer;
?>

<div class="container space-layout-container">
    <div class="row">
        <div class="col-md-12">
            <?= \humhub\modules\stats\widgets\CustomSpaceHeader::widget(['space' => $space]); ?>
            <?php //echo humhub\modules\space\widgets\Header::widget(['space' => $space]); ?>
        </div>

```
</div>
<div class="row">
    <div class="col-md-2 layout-nav-container">
        <?php echo \humhub\modules\space\widgets\Menu::widget(['space' => $space]); ?>
```
1. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/srv/www/dev.humhub.m00.com.br/t...')
2. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/srv/www/dev.humhub.m00.com.br/t...', ['content' => '<div class="panel panel-default"...'])
3. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/srv/www/dev.humhub.m00.com.br/p...', ['content' => '<div class="panel panel-default"...'], null)
4. in /srv/www/dev.humhub.m00.com.br/themes/Evoke/views/layouts/main.php at line 120 – yii\base\View::render('@humhub/modules/space/views/spac...', ['content' => '<div class="panel panel-default"...'])
   114115116117118119120121122123124125126    
   
   <?php echo \humhub\modules\tour\widgets\Tour::widget(); ?>
   
   
   
   <?php if (isset($this->context->subLayout) && $this->context->subLayout != "") : ?>
       <?php echo $this->render($this->context->subLayout, array('content' => $content)); ?>
   <?php else: ?>
       <?php echo $content; ?>
   <?php endif; ?>
   
   
   
   
5. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/srv/www/dev.humhub.m00.com.br/t...')
6. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/srv/www/dev.humhub.m00.com.br/t...', ['content' => '<div class="panel panel-default"...'])
7. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Controller.php at line 392 – yii\base\View::renderFile('/srv/www/dev.humhub.m00.com.br/p...', ['content' => '<div class="panel panel-default"...'], humhub\modules\missions\controllers\ReviewController)
8. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Controller.php at line 378 – yii\base\Controller::renderContent('<div class="panel panel-default"...')
9. in /srv/www/dev.humhub.m00.com.br/protected/modules/missions/controllers/ReviewController.php at line 104 – yii\base\Controller::render('index', ['contentContainer' => humhub\modules\space\models\Space, 'evidence' => null, 'files' => null, 'evidence_count' => '0', ...])
   9899100101102103104105106107        $totalEvidence = $this->getEvidenceToReviewCount($this->contentContainer);
   
   ```
   if($this->contentContainer->name == "Mentors" && $user->group->name != "Mentors"){
       $this->redirect($this->contentContainer->createUrl());
   }
   
   return $this->render('index', array('contentContainer' => $this->contentContainer, 'evidence' => $evidence, 'files' => $files, 'evidence_count' => $totalEvidence, 'evidence_to_review_count' => $evidence_to_review_count));
   ```
   
   }

}
19. humhub\modules\missions\controllers\ReviewController::actionIndex()
20. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\missions\controllers\ReviewController, 'actionIndex'], [])
21. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'missions/review/index', 'sguid' => '21dc8809-30d5-4d7a-871d-bc09f13f...'])
22. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('index', ['r' => 'missions/review/index', 'sguid' => '21dc8809-30d5-4d7a-871d-bc09f13f...'])
23. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('missions/review/index', ['r' => 'missions/review/index', 'sguid' => '21dc8809-30d5-4d7a-871d-bc09f13f...'])
24. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
25. in /srv/www/dev.humhub.m00.com.br/index.php at line 25 – yii\base\Application::run()
19202122232425    require(**DIR** . '/protected/humhub/config/web.php'),
    (is_readable(**DIR** . '/protected/config/dynamic.php')) ? require(**DIR** . '/protected/config/dynamic.php') : [],
    require(**DIR** . '/protected/config/common.php'),
    require(**DIR** . '/protected/config/web.php')
);

(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'missions/review/index',
    'sguid' => '21dc8809-30d5-4d7a-871d-bc09f13f8e11',
];

$_COOKIE = [
    '_csrf' => '300058683ebf01dd80e043f4e918e6734aa73c15714aa5a39475a6a3da7681e1a:2:{i:0;s:5:"_csrf";i:1;s:32:"GRNojp_o59wcW3OzVwnhz08fZxMgfPiN";}',
    'pm_space-members-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'pm_profile-follower-panel' => 'expanded',
    'pm_profile-following-panel' => 'expanded',
    'pm_groups-statistics-panel' => 'expanded',
    'pm_new-spaces-panel' => 'expanded',
    'pm_new-people-panel' => 'expanded',
    'pm_user-statistics-panel' => 'expanded',
    'language' => '21351261ae4d81ca3f5873a42e399a283387c65465209c43ef5571abea4dc6c1a:2:{i:0;s:8:"language";i:1;s:2:"es";}',
    'PHPSESSID' => 'lognhn3d2brmbnfnj0fd13llc1',
    '_identity' => '276de92d0ab515b0398955cd432b6c9ede0ac43f15ecccb46fb05ce1e56cf4e0a:2:{i:0;s:9:"_identity";i:1;s:51:"[60,"2a049146-73d4-463e-9ac9-444b413c7bab",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/index.php',
    '__id' => 60,
];
Yii Framework
2016-08-04, 16:49:26

Apache
Yii Framework/2.0.7

**Comment by JayantGandhi** [comment]
This is my fault. I deleted all the activities by accident.
