### ISSUE TITLE
Activity stream not in chronological order

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#82]
See attached screenshot

<img width="427" alt="activity_stream_not_in_order" src="https://cloud.githubusercontent.com/assets/273429/17420919/80f549ce-5a6b-11e6-9166-a6832eaac431.png">

**Comment by rjapur** [comment]
getting in touch with lucas to see how to solve this

**Comment by nathanverrill** [comment]
Closing and adding a feature for this in Pivotal, since this has been addressed from a UX perspective by hiding them.
