### ISSUE TITLE
Can't turn off evokations

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#83]
I turned on evokations and set a deadline - In Evoke Settings and Evokation Deadline section.

I want to turn it off, and unchecked it in Evoke Settings and deleted the deadline, and the evokation page is still present on the site.

**Comment by Guihrmsfo** [comment]
Evokations are turned off, you still can see the page, but evokation submission button and portfolio aren't showed.
Should I remove evokation page as well?

**Comment by nathanverrill** [comment]
yes

**Comment by nathanverrill** [comment]
In addition, and as a point of clarification, the Admin can toggle on/off whether the Evokation page is displayed. (not in team space navigation on left)
