### ISSUE TITLE
PHP error on search

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#86]
Hit magnifying glass, enter Nathan Verrill as search phrase

Exception – yii\base\Exception

Could not determine container type!
1. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/content/models/Content.php at line 631
622623624625626627628629630631632633634635636637638639640        if ($this->_container != null) {
            return $this->_container;
        }

```
    if ($this->space_id != null) {
        $container = $this->space;
    } elseif ($this->user_id != null) {
        $container = $this->user;
    } else {
        throw new Exception("Could not determine container type!");
    }

    $this->_container = $container;

    return $this->_container;
}

public function beforeValidate()
{
```
1. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Component.php at line 130 – humhub\modules\content\models\Content::getContainer()
2. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 247 – yii\base\Component::__get('container')
3. in /srv/www/dev.humhub.m00.com.br/themes/Evoke/views/content/widgets/wallEntry.php at line 10 – yii\db\BaseActiveRecord::__get('container')
   45678910111213141516use humhub\modules\space\models\Space;
   use humhub\modules\user\models\User;
   use humhub\modules\content\components\ContentContainerController;
   use app\modules\teams\models\Team;

$user = $object->content->user;
$container = $object->content->container;

$team_id = Team::getUserTeam($user->id);
if($team_id){
    $team = Team::findOne($team_id);
}else{
    $team = null;
5. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/srv/www/dev.humhub.m00.com.br/t...')
6. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/srv/www/dev.humhub.m00.com.br/t...', ['content' => ' <span id="post-content-60" styl...', 'object' => humhub\modules\post\models\Post, 'wallEntryWidget' => humhub\modules\post\widgets\WallEntry])
7. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/srv/www/dev.humhub.m00.com.br/p...', ['content' => ' <span id="post-content-60" styl...', 'object' => humhub\modules\post\models\Post, 'wallEntryWidget' => humhub\modules\post\widgets\WallEntry], humhub\modules\post\widgets\WallEntry)
8. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Widget.php at line 191 – yii\base\View::render('@humhub/modules/content/widgets/...', ['content' => ' <span id="post-content-60" styl...', 'object' => humhub\modules\post\models\Post, 'wallEntryWidget' => humhub\modules\post\widgets\WallEntry], humhub\modules\post\widgets\WallEntry)
9. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/content/widgets/WallEntry.php at line 112 – yii\base\Widget::render('@humhub/modules/content/widgets/...', ['content' => ' <span id="post-content-60" styl...', 'object' => humhub\modules\post\models\Post, 'wallEntryWidget' => humhub\modules\post\widgets\WallEntry])
106107108109110111112113114115116117118        ob_implicit_flush(false);
        try {
            $out = $this->render($this->wallEntryLayout, [
                'content' => $this->run(),
                'object' => $this->contentObject,
                'wallEntryWidget' => $this
            ]);
        } catch (\Exception $e) {
            ob_end_clean();
            throw $e;
        }

```
    return ob_get_clean() . $out;
```
1. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/content/components/ContentActiveRecord.php at line 124 – humhub\modules\content\widgets\WallEntry::renderWallEntry()
   118119120121122123124125126127128129130     */
   public function getWallOut($params = [])
   {
       $wallEntryWidget = $this->getWallEntryWidget();
       if ($wallEntryWidget !== null) {
           Yii::configure($wallEntryWidget, $params);
           return $wallEntryWidget->renderWallEntry();
       }
       return "";
   }
   
   /**
   - Returns the assigned wall entry widget instance
2. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/search/views/search/index.php at line 108 – humhub\modules\content\components\ContentActiveRecord::getWallOut()
   102103104105106107108109110111112113114                <div class="searchResults">
   
   ```
               <?php if (count($results) > 0): ?>
                   <?php foreach ($results as $result): ?>
   
                       <?php if ($result instanceof ContentActiveRecord || $result instanceof ContentContainerActiveRecord) : ?>
                           <?php echo $result->getWallOut(); ?>
                       <?php else: ?>
                           No Output for Class <?php echo get_class($result); ?>
                       <?php endif; ?>
                   <?php endforeach; ?>
               <?php else: ?>
                   <p>Sorry nothing found :(</p>
   ```
3. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 325 – require('/srv/www/dev.humhub.m00.com.br/p...')
4. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 247 – yii\base\View::renderPhpFile('/srv/www/dev.humhub.m00.com.br/p...', ['scope' => 'all', 'keyword' => 'nathan verrill', 'results' => [humhub\modules\user\models\User, humhub\modules\user\models\User, humhub\modules\user\models\User, humhub\modules\user\models\User, ...], 'pagination' => yii\data\Pagination, ...])
5. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/View.php at line 149 – yii\base\View::renderFile('/srv/www/dev.humhub.m00.com.br/p...', ['scope' => 'all', 'keyword' => 'nathan verrill', 'results' => [humhub\modules\user\models\User, humhub\modules\user\models\User, humhub\modules\user\models\User, humhub\modules\user\models\User, ...], 'pagination' => yii\data\Pagination, ...], humhub\modules\search\controllers\SearchController)
6. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Controller.php at line 377 – yii\base\View::render('index', ['scope' => 'all', 'keyword' => 'nathan verrill', 'results' => [humhub\modules\user\models\User, humhub\modules\user\models\User, humhub\modules\user\models\User, humhub\modules\user\models\User, ...], 'pagination' => yii\data\Pagination, ...], humhub\modules\search\controllers\SearchController)
7. in /srv/www/dev.humhub.m00.com.br/protected/humhub/modules/search/controllers/SearchController.php at line 94 – yii\base\Controller::render('index', ['scope' => 'all', 'keyword' => 'nathan verrill', 'results' => [humhub\modules\user\models\User, humhub\modules\user\models\User, humhub\modules\user\models\User, humhub\modules\user\models\User, ...], 'pagination' => yii\data\Pagination, ...])
   888990919293949596979899100            'scope' => $scope,
           'keyword' => $keyword,
           'results' => $searchResultSet->getResultInstances(),
           'pagination' => $pagination,
           'totals' => $this->getTotals($keyword, $options),
           'limitSpaceGuids' => $limitSpaceGuids
       ));
   }
   
   /**
   - JSON Search interface for Mentioning
     */
     public function actionMentioning()
8. humhub\modules\search\controllers\SearchController::actionIndex()
9. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/InlineAction.php at line 55 – call_user_func_array([humhub\modules\search\controllers\SearchController, 'actionIndex'], [])
10. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Controller.php at line 154 – yii\base\InlineAction::runWithParams(['r' => 'search/search/index', 'keyword' => 'nathan verrill', 'limitSpaceGuids' => ''])
11. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Module.php at line 454 – yii\base\Controller::runAction('index', ['r' => 'search/search/index', 'keyword' => 'nathan verrill', 'limitSpaceGuids' => ''])
12. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/web/Application.php at line 84 – yii\base\Module::runAction('search/search/index', ['r' => 'search/search/index', 'keyword' => 'nathan verrill', 'limitSpaceGuids' => ''])
13. in /srv/www/dev.humhub.m00.com.br/protected/vendor/yiisoft/yii2/base/Application.php at line 375 – yii\web\Application::handleRequest(humhub\components\Request)
14. in /srv/www/dev.humhub.m00.com.br/index.php at line 25 – yii\base\Application::run()
    19202122232425    require(**DIR** . '/protected/humhub/config/web.php'),
    (is_readable(**DIR** . '/protected/config/dynamic.php')) ? require(**DIR** . '/protected/config/dynamic.php') : [],
    require(**DIR** . '/protected/config/common.php'),
    require(**DIR** . '/protected/config/web.php')
    );

(new humhub\components\Application($config))->run();
 $_GET = [
    'r' => 'search/search/index',
    'keyword' => 'nathan verrill',
    'limitSpaceGuids' => '',
];

$_COOKIE = [
    '_csrf' => '224aa7ee4562eee254472306dabb6ae07eb6b51a0e9f65c45e501c7ae2c9dd36a:2:{i:0;s:5:"_csrf";i:1;s:32:"mUF5nHKv-RSsVkmIAWSAknfqFUDRKtCC";}',
    'pm_space-members-panel' => 'expanded',
    'pm_user-tags-panel' => 'expanded',
    'pm_user-spaces-panel' => 'expanded',
    'pm_profile-following-panel' => 'expanded',
    'language' => '21351261ae4d81ca3f5873a42e399a283387c65465209c43ef5571abea4dc6c1a:2:{i:0;s:8:"language";i:1;s:2:"es";}',
    'PHPSESSID' => 'g67c2f4bf6mgnqq5i0dotca9g6',
    '_identity' => '7c95287fe24b33885820e3e0f85daf9a51c76a7662295acd30b06f3d5bc371f0a:2:{i:0;s:9:"_identity";i:1;s:52:"[181,"5ca923e8-84f6-498f-9193-d638e8e36395",2592000]";}',
];

$_SESSION = [
    '__flash' => [],
    '__returnUrl' => '/index.php',
    '__id' => 181,
];
Yii Framework
2016-08-05, 15:54:48

Apache
Yii Framework/2.0.7

**Comment by nathanverrill** [comment]
When I search for "Bob" I don't get this error.

**Comment by Guihrmsfo** [comment]
Database issue: There was a post object with not relation with a content object. 
I'm working on a prevention feature to this particular case and later on I'll look for similar cases to exclude them from database.
