### ISSUE TITLE
Mentor vote on +10 curiosity evidence only adds +5

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#87]
I reviewed this evidence as a mentor:

http://dev.humhub.m00.com.br/index.php?r=content%2Fperma&id=563

Before I reviewed the evidence, the player had 14 Curiosity.

I gave it a +5 as a mentor and the player only received +5. Should they receive +10?

Mentor user: Mentor August 5th

Mentor's password is Soacha

**Comment by Guihrmsfo** [comment]
@nathanverrill 
Can you test it, please?
