### ISSUE TITLE
Cannot Reset Password

### ISSUE THREAD

**Issue by JayantGandhi** [EvokeNet/humhub#90]
asks for security code above but there is no security code to refer to.

**Comment by rjapur** [comment]
getting in touch with lucas to see how to solve this

**Comment by nathanverrill** [comment]
What's the status on this issue?

**Comment by nathanverrill** [comment]
Can you guys figure this out before hearing from Lucas? 

Since this is such a small trusted network, perhaps remove the captcha ID altogether?
