### ISSUE TITLE
Fix alignment on the powers display

### ISSUE THREAD

**Issue by JayantGandhi** [EvokeNet/humhub#91]
![powers](https://cloud.githubusercontent.com/assets/4398613/17489692/5bfe537c-5d6d-11e6-91e5-061b547787fe.png)

**Comment by JayantGandhi** [comment]
power bars should line up

**Comment by nathanverrill** [comment]
Also, don't gray out any of the powers. Only the level 0 super powers.

**Comment by nathanverrill** [comment]
I'm closing this since it is covered by the pivotal task for updating the layout
